[versions]
android-sdk-min = "29"
android-sdk-target = "34"
android-sdk-compile = "34"
agp = "8.3.0"
kotlin = "1.9.22"
core-ktx = "1.12.0"
junit = "4.13.2"
appcompat = "1.6.1"
material = "1.11.0"
compose-bom = "2024.02.02"
compose-activity = "1.8.2"
compose-compiler = "1.5.8"
compose-navigation = "2.7.7"
google-services = "4.4.1"
firebase-appdistribution = "4.2.0"
ktlint = "12.1.0"

[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-material = { group = "androidx.compose.material", name = "material" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "compose-activity" }
compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "compose-navigation" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
googleServices = { id = "com.google.gms.google-services", version.ref = "google-services" }
firebaseAppdistribution = { id = "com.google.firebase.appdistribution", version.ref = "firebase-appdistribution" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }

