@file:Suppress("ktlint")

/*
 * EAfspraakAppointment.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.hcimParser.uiSchema.models

import kotlinx.serialization.Serializable

@Serializable
data class EAfspraakAppointment(
    val patientInstructions: List<ExtensionValue_Of_MgoString>,
    val identifier: List<MgoIdentifier>? = null,
    val appointmentType: MgoCodeableConcept? = null,
    val reason: List<MgoCodeableConcept>? = null,
    val specialty: List<MgoCodeableConcept>? = null,
    val incomingReferral: List<MgoReference>? = null,
    val created: MgoDateTime? = null,
    val profile: String = "http://nictiz.nl/fhir/StructureDefinition/eAfspraak-Appointment",
    val start: MgoDateTime? = null,
    val description: MgoString? = null,
    val minutesDuration: MgoPositiveInt? = null,
    val serviceCategory: MgoCodeableConcept? = null,
    val participant: List<Participant>? = null,
    val referenceId: String,
    val onlineEditable: ExtensionValue_Of_structure_0_015396199392011534? = null,
    val fhirVersion: String = "R3",
    val end: MgoDateTime? = null,
    val indication: List<MgoReference>? = null,
    val id: String? = null,
    val status: Status,
    val resourceType: String
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str1) { "fhirVersion not constant value $cg_str1 - $fhirVersion" }
    }

    @Serializable
    data class Participant(
        val actor: MgoReference? = null,
        val type: Type,
        val required: MgoCode_Of_required_optional_information_only? = null,
        val status: MgoCode_Of_accepted_declined_tentative_needs_action? = null
    )

    @Serializable
    data class Type(
        val healthProfessionalRole: List<MgoCodeableConcept>? = null
    )

    @Serializable
    data class Status(
        val _type: String? = null,
        val orderStatus: ExtensionValue_Of_MgoCodeableConcept? = null,
        val value: String? = null
    ) {

        init {
            if (_type != null)
                require(_type == cg_str2) { "_type not constant value $cg_str2 - $_type" }
            if (value != null)
                require(value in cg_array3) { "value not in enumerated values - $value" }
        }

    }

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/eAfspraak-Appointment"
        private const val cg_str1 = "R3"
        private const val cg_str2 = "code"
        private val cg_array3 = setOf(
            "cancelled",
            "entered-in-error",
            "proposed",
            "pending",
            "booked",
            "arrived",
            "fulfilled",
            "noshow"
        )
    }

}
