@file:Suppress("ktlint")

/*
 * ExtensionValue_Of_MgoDuration.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.hcimParser.uiSchema.models

import kotlin.Double

import kotlinx.serialization.Serializable

@Serializable
data class ExtensionValue_Of_MgoDuration(
    val comparator: String? = null,
    val unit: String? = null,
    val system: String? = null,
    val code: String? = null,
    val _type: String = "duration",
    val value: Double? = null,
    val _ext: Boolean
) {

    init {
        require(_type == cg_str0) { "_type not constant value $cg_str0 - $_type" }
    }

    companion object {
        private const val cg_str0 = "duration"
    }

}
