@file:Suppress("ktlint")

/*
 * ExtensionValue_Of_MgoCodeableConcept.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.hcimParser.uiSchema.models

import kotlinx.serialization.Serializable

@Serializable
data class ExtensionValue_Of_MgoCodeableConcept(
    val coding: List<MgoCodingProps>,
    val _type: String = "codeableConcept",
    val text: String? = null,
    val _ext: Boolean
) {

    init {
        require(_type == cg_str0) { "_type not constant value $cg_str0 - $_type" }
    }

    companion object {
        private const val cg_str0 = "codeableConcept"
    }

}
