@file:Suppress("ktlint")

/*
 * ExtensionValue_Of_structure_0_22151697474263576.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.hcimParser.uiSchema.models

import kotlinx.serialization.Serializable

@Serializable
data class ExtensionValue_Of_structure_0_22151697474263576(
    val verifiedWith: ExtensionValue_Of_MgoCodeableConcept? = null,
    val verified: ExtensionValue_Of_MgoBoolean? = null,
    val _ext: Boolean,
    val verificationDate: ExtensionValue_Of_MgoDateTime? = null
)
