@file:Suppress("ktlint")

/*
 * ExtensionValue_Of_structure_0_6188193043771031.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.hcimParser.uiSchema.models

import kotlinx.serialization.Serializable

@Serializable
data class ExtensionValue_Of_structure_0_6188193043771031(
    val bankName: ExtensionValue_Of_MgoString? = null,
    val accountNumber: ExtensionValue_Of_MgoString? = null,
    val _ext: Boolean,
    val bankcode: ExtensionValue_Of_MgoString? = null
)
