@file:Suppress("ktlint")

/*
 * HcimCardDetails.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.hcimParser.uiSchema.models

import kotlinx.serialization.Serializable

@Serializable
data class HcimCardDetails(
    val descriptionIcon: String? = null,
    val description: String? = null,
    val detail: String? = null,
    val title: String
) {

    init {
        if (descriptionIcon != null)
            require(descriptionIcon in cg_array0) { "descriptionIcon not in enumerated values - $descriptionIcon" }
    }

    companion object {
        private val cg_array0 = setOf(
            "calendar_today",
            "favorite-fill"
        )
    }

}
