@file:Suppress("ktlint")

/*
 * IheMhdMinimalDocumentReference.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.hcimParser.uiSchema.models

import kotlinx.serialization.Serializable

@Serializable
data class IheMhdMinimalDocumentReference(
    val identifier: List<MgoIdentifier>? = null,
    val indexed: MgoInstant? = null,
    val subject: MgoReference? = null,
    val author: List<MgoReference>? = null,
    val securityLabel: List<MgoCodeableConcept>? = null,
    val profile: String = "http://nictiz.nl/fhir/StructureDefinition/IHE.MHD.Minimal.DocumentReference",
    val masterIdentifier: MgoIdentifier? = null,
    val type: MgoCodeableConcept? = null,
    val content: Content,
    val referenceId: String,
    val fhirVersion: String = "R3",
    val context: Context,
    val id: String? = null,
    val relatesTo: List<RelatesTo>? = null,
    val `class`: MgoCodeableConcept? = null,
    val status: MgoCode_Of_entered_in_error_current_superseded? = null,
    val resourceType: String
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str1) { "fhirVersion not constant value $cg_str1 - $fhirVersion" }
    }

    @Serializable
    data class Content(
        val attachment: MgoAttachment? = null,
        val format: MgoCoding? = null
    )

    @Serializable
    data class Context(
        val period: MgoPeriod? = null,
        val facilityType: MgoCodeableConcept? = null,
        val practiceSetting: MgoCodeableConcept? = null,
        val sourcePatientInfo: MgoReference? = null
    )

    @Serializable
    data class RelatesTo(
        val target: MgoReference? = null
    )

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/IHE.MHD.Minimal.DocumentReference"
        private const val cg_str1 = "R3"
    }

}
