@file:Suppress("ktlint")

/*
 * MgoSimpleQuantityProps.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.hcimParser.uiSchema.models

import kotlin.Double

import kotlinx.serialization.Serializable

@Serializable
data class MgoSimpleQuantityProps(
    val unit: String? = null,
    val system: String? = null,
    val code: String? = null,
    val value: Double? = null
)
