@file:Suppress("ktlint")

/*
 * MgoSimpleQuantity.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.hcimParser.uiSchema.models

import kotlin.Double

import kotlinx.serialization.Serializable

@Serializable
data class MgoSimpleQuantity(
    val unit: String? = null,
    val system: String? = null,
    val code: String? = null,
    val _type: String = "simpleQuantity",
    val value: Double? = null
) {

    init {
        require(_type == cg_str0) { "_type not constant value $cg_str0 - $_type" }
    }

    companion object {
        private const val cg_str0 = "simpleQuantity"
    }

}
