@file:Suppress("ktlint")

/*
 * NlCoreOrganization.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.hcimParser.uiSchema.models

import kotlinx.serialization.Serializable

@Serializable
data class NlCoreOrganization(
    val identifier: List<MgoIdentifier>? = null,
    val address: List<Addres>? = null,
    val profile: String = "http://fhir.nl/fhir/StructureDefinition/nl-core-organization",
    val fhirVersion: String = "R3",
    val name: MgoString? = null,
    val alias: List<MgoString>? = null,
    val telecom: List<Telecom>? = null,
    val id: String? = null,
    val type: Type,
    val referenceId: String,
    val resourceType: String
) {

    init {
        require(profile == cg_str1) { "profile not constant value $cg_str1 - $profile" }
        require(fhirVersion == cg_str2) { "fhirVersion not constant value $cg_str2 - $fhirVersion" }
    }

    @Serializable
    data class Addres(
        val country: MgoString? = null,
        val _profile: String,
        val city: MgoString? = null,
        val addressType: MgoCodeableConcept? = null,
        val use: MgoCode_Of_string? = null,
        val line: List<Line>? = null,
        val district: MgoString? = null,
        val postalCode: MgoString? = null,
        val official: MgoBoolean? = null,
        val type: MgoCode_Of_string? = null
    ) {

        init {
            require(_profile == cg_str0) { "_profile not constant value $cg_str0 - $_profile" }
        }

    }

    @Serializable
    data class Line(
        val streetName: MgoString? = null,
        val buildingNumberSuffix: MgoString? = null,
        val additionalLocator: MgoString? = null,
        val houseNumber: MgoString? = null,
        val unitId: MgoString? = null
    )

    @Serializable
    data class Telecom(
        val system: MgoCode_Of_string? = null,
        val _profile: String,
        val use: MgoCode_Of_string? = null,
        val telecomType: MgoCodeableConcept? = null,
        val value: MgoString? = null
    ) {

        init {
            require(_profile == cg_str3) { "_profile not constant value $cg_str3 - $_profile" }
        }

    }

    @Serializable
    data class Type(
        val organizationType: List<MgoCodeableConcept>? = null,
        val departmentSpecialty: List<MgoCodeableConcept>? = null
    )

    companion object {
        private const val cg_str0 = "http://fhir.nl/fhir/StructureDefinition/nl-core-address"
        private const val cg_str1 = "http://fhir.nl/fhir/StructureDefinition/nl-core-organization"
        private const val cg_str2 = "R3"
        private const val cg_str3 = "http://fhir.nl/fhir/StructureDefinition/nl-core-contactpoint"
    }

}
