@file:Suppress("ktlint")

/*
 * NlCoreCarePlan.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.hcimParser.uiSchema.models

import kotlinx.serialization.Serializable

@Serializable
data class NlCoreCarePlan(
    val identifier: List<MgoIdentifier>? = null,
    val period: MgoPeriod? = null,
    val goal: List<MgoReference>? = null,
    val activity: List<Activity>? = null,
    val subject: MgoReference? = null,
    val profile: String = "http://fhir.nl/fhir/StructureDefinition/nl-core-careplan",
    val fhirVersion: String = "R3",
    val id: String? = null,
    val referenceId: String,
    val resourceType: String
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str1) { "fhirVersion not constant value $cg_str1 - $fhirVersion" }
    }

    @Serializable
    data class Activity(
        val nursingIntervention: NursingIntervention
    )

    @Serializable
    data class NursingIntervention(
        val reference: MgoReference? = null,
        val outcomeCodeableConcept: List<MgoCodeableConcept>? = null,
        val outcomeReference: List<MgoReference>? = null,
        val comment: ExtensionValue_Of_MgoString? = null,
        val detail: Detail
    )

    @Serializable
    data class Detail(
        val code: MgoCodeableConcept? = null,
        val goal: List<MgoReference>? = null,
        val performer: List<MgoReference>? = null,
        val scheduledTiming: MgoTiming? = null,
        val medicalDevice: List<ExtensionValue_Of_MgoReference>,
        val reasonReference: List<MgoReference>? = null,
        val description: MgoString? = null
    )

    companion object {
        private const val cg_str0 = "http://fhir.nl/fhir/StructureDefinition/nl-core-careplan"
        private const val cg_str1 = "R3"
    }

}
