@file:Suppress("ktlint")

/*
 * NlCoreAddressStreetNameHouseNumber.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.hcimParser.uiSchema.models

import kotlinx.serialization.Serializable

@Serializable
data class NlCoreAddressStreetNameHouseNumber(
    val streetName: MgoString? = null,
    val additionalLocator: MgoString? = null,
    val buildingNumbersuffix: MgoString? = null,
    val houseNumber: MgoString? = null,
    val unitID: MgoString? = null
)
