@file:Suppress("ktlint")

/*
 * NlCoreObservation.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.hcimParser.uiSchema.models

import kotlinx.serialization.Serializable

@Serializable
data class NlCoreObservation(
    val identifier: List<MgoIdentifier>? = null,
    val performer: List<MgoReference>? = null,
    val effectivePeriod: MgoPeriod? = null,
    val effectiveDateTime: MgoDateTime? = null,
    val subject: MgoReference? = null,
    val profile: String = "http://fhir.nl/fhir/StructureDefinition/nl-core-observation",
    val fhirVersion: String = "R3",
    val id: String? = null,
    val referenceId: String,
    val resourceType: String
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str1) { "fhirVersion not constant value $cg_str1 - $fhirVersion" }
    }

    companion object {
        private const val cg_str0 = "http://fhir.nl/fhir/StructureDefinition/nl-core-observation"
        private const val cg_str1 = "R3"
    }

}
