@file:Suppress("ktlint")

/*
 * NlCoreCareTeam.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.hcimParser.uiSchema.models

import kotlinx.serialization.Serializable

@Serializable
data class NlCoreCareTeam(
    val identifier: List<MgoIdentifier>? = null,
    val period: MgoPeriod? = null,
    val subject: MgoReference? = null,
    val profile: String = "http://fhir.nl/fhir/StructureDefinition/nl-core-careteam",
    val fhirVersion: String = "R3",
    val id: String? = null,
    val participant: List<Participant>? = null,
    val referenceId: String,
    val resourceType: String
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str1) { "fhirVersion not constant value $cg_str1 - $fhirVersion" }
    }

    @Serializable
    data class Participant(
        val participant: MgoReference? = null,
        val healthProfessionalRole: MgoCodeableConcept? = null
    )

    companion object {
        private const val cg_str0 = "http://fhir.nl/fhir/StructureDefinition/nl-core-careteam"
        private const val cg_str1 = "R3"
    }

}
