@file:Suppress("ktlint")

/*
 * NlCoreRelatedPerson.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.hcimParser.uiSchema.models

import kotlinx.serialization.Serializable

@Serializable
data class NlCoreRelatedPerson(
    val identifier: List<MgoIdentifier>? = null,
    val period: MgoPeriod? = null,
    val address: List<Addres>? = null,
    val role: ExtensionValue_Of_MgoCodeableConcept? = null,
    val profile: String = "http://fhir.nl/fhir/StructureDefinition/nl-core-relatedperson",
    val referenceId: String,
    val patient: MgoReference? = null,
    val fhirVersion: String = "R3",
    val name: List<Name>? = null,
    val telecom: List<Telecom>? = null,
    val id: String? = null,
    val relationship: MgoCodeableConcept? = null,
    val resourceType: String
) {

    init {
        require(profile == cg_str1) { "profile not constant value $cg_str1 - $profile" }
        require(fhirVersion == cg_str2) { "fhirVersion not constant value $cg_str2 - $fhirVersion" }
    }

    @Serializable
    data class Addres(
        val country: MgoString? = null,
        val _profile: String,
        val city: MgoString? = null,
        val addressType: MgoCodeableConcept? = null,
        val use: MgoCode_Of_string? = null,
        val line: List<Line>? = null,
        val district: MgoString? = null,
        val postalCode: MgoString? = null,
        val official: MgoBoolean? = null,
        val type: MgoCode_Of_string? = null
    ) {

        init {
            require(_profile == cg_str0) { "_profile not constant value $cg_str0 - $_profile" }
        }

    }

    @Serializable
    data class Line(
        val streetName: MgoString? = null,
        val buildingNumberSuffix: MgoString? = null,
        val additionalLocator: MgoString? = null,
        val houseNumber: MgoString? = null,
        val unitId: MgoString? = null
    )

    @Serializable
    data class Name(
        val given: Given,
        val _profile: String,
        val humannameAssemblyOrder: MgoCode_Of_string? = null,
        val text: MgoString? = null,
        val family: Family
    ) {

        init {
            require(_profile == cg_str3) { "_profile not constant value $cg_str3 - $_profile" }
        }

    }

    @Serializable
    data class Given(
        val initials: List<MgoString>? = null,
        val callName: List<MgoString>? = null,
        val birthName: List<MgoString>? = null
    )

    @Serializable
    data class Family(
        val humannamePartnerPrefix: MgoString? = null,
        val humannameOwnPrefix: MgoString? = null,
        val humannameOwnName: MgoString? = null,
        val humannamePartnerName: MgoString? = null
    )

    @Serializable
    data class Telecom(
        val system: MgoCode_Of_string? = null,
        val _profile: String,
        val use: MgoCode_Of_string? = null,
        val telecomType: MgoCodeableConcept? = null,
        val value: MgoString? = null
    ) {

        init {
            require(_profile == cg_str4) { "_profile not constant value $cg_str4 - $_profile" }
        }

    }

    companion object {
        private const val cg_str0 = "http://fhir.nl/fhir/StructureDefinition/nl-core-address"
        private const val cg_str1 = "http://fhir.nl/fhir/StructureDefinition/nl-core-relatedperson"
        private const val cg_str2 = "R3"
        private const val cg_str3 = "http://fhir.nl/fhir/StructureDefinition/nl-core-humanname"
        private const val cg_str4 = "http://fhir.nl/fhir/StructureDefinition/nl-core-contactpoint"
    }

}
