@file:Suppress("ktlint")

/*
 * PrimitiveValueType_Of_code__has_member_derived_from_sequel_to_replaces_qualified_by_interfered_by.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.hcimParser.uiSchema.models

import kotlinx.serialization.Serializable

@Serializable
data class PrimitiveValueType_Of_code__has_member_derived_from_sequel_to_replaces_qualified_by_interfered_by(
    val _type: String = "code",
    val value: String
) {

    init {
        require(_type == cg_str0) { "_type not constant value $cg_str0 - $_type" }
        require(value in cg_array1) { "value not in enumerated values - $value" }
    }

    companion object {
        private const val cg_str0 = "code"
        private val cg_array1 = setOf(
            "has-member",
            "derived-from",
            "sequel-to",
            "replaces",
            "qualified-by",
            "interfered-by"
        )
    }

}
