@file:Suppress("ktlint")

/*
 * R4BbsDocumentReference.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.hcimParser.uiSchema.models

import kotlinx.serialization.Serializable

@Serializable
data class R4BbsDocumentReference(
    val date: MgoDateTime? = null,
    val subject: MgoReference? = null,
    val author: List<MgoReference>? = null,
    val profile: String = "http://medmij.nl/fhir/StructureDefinition/bbs-DocumentReference",
    val fhirVersion: String = "R4",
    val context: Context,
    val id: String? = null,
    val masterIdentifier: MgoIdentifier? = null,
    val type: MgoCodeableConcept? = null,
    val content: List<Content>? = null,
    val referenceId: String,
    val resourceType: String
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str1) { "fhirVersion not constant value $cg_str1 - $fhirVersion" }
    }

    @Serializable
    data class Context(
        val period: MgoPeriod? = null,
        val facilityType: MgoCodeableConcept? = null,
        val practiceSetting: MgoCodeableConcept? = null,
        val sourcePatientInfo: MgoReference? = null
    )

    @Serializable
    data class Content(
        val attachment: MgoAttachment? = null,
        val format: MgoCoding? = null
    )

    companion object {
        private const val cg_str0 = "http://medmij.nl/fhir/StructureDefinition/bbs-DocumentReference"
        private const val cg_str1 = "R4"
    }

}
