@file:Suppress("ktlint")

/*
 * R4NlCoreNameInformation.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.hcimParser.uiSchema.models

import kotlinx.serialization.Serializable

@Serializable
data class R4NlCoreNameInformation(
    val given: Given,
    val period: MgoPeriod? = null,
    val _profile: String = "http://nictiz.nl/fhir/StructureDefinition/zib-NameInformation",
    val prefix: List<MgoString>? = null,
    val text: MgoString? = null,
    val family: Family,
    val suffix: List<MgoString>? = null
) : R4NlCorePatientPropertiesContactItemsPropertiesName {

    init {
        require(_profile == cg_str0) { "_profile not constant value $cg_str0 - $_profile" }
    }

    @Serializable
    data class Given(
        val initials: List<MgoString>? = null,
        val birthName: List<MgoString>? = null
    )

    @Serializable
    data class Family(
        val humannamePartnerPrefix: MgoString? = null,
        val humannameOwnPrefix: MgoString? = null,
        val humannameOwnName: MgoString? = null,
        val humannamePartnerName: MgoString? = null
    )

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/zib-NameInformation"
    }

}
