@file:Suppress("ktlint")

/*
 * R4NlCoreHealthProfessionalPractitioner.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.hcimParser.uiSchema.models

import kotlinx.serialization.Serializable

@Serializable
data class R4NlCoreHealthProfessionalPractitioner(
    val identifier: List<MgoIdentifier>? = null,
    val address: List<Addres>? = null,
    val gender: MgoCode_Of_unknown_male_female_other? = null,
    val profile: String = "http://nictiz.nl/fhir/StructureDefinition/nl-core-HealthProfessional-Practitioner",
    val fhirVersion: String = "R4",
    val name: List<R4NlCoreHealthProfessionalPractitionerName>? = null,
    val telecom: R4NlCoreContactInformation,
    val id: String? = null,
    val referenceId: String,
    val resourceType: String
) {

    init {
        require(profile == cg_str1) { "profile not constant value $cg_str1 - $profile" }
        require(fhirVersion == cg_str2) { "fhirVersion not constant value $cg_str2 - $fhirVersion" }
    }

    @Serializable
    data class Addres(
        val country: Country,
        val _profile: String,
        val city: MgoString? = null,
        val use: MgoCode_Of_string? = null,
        val line: List<Line>? = null,
        val district: MgoString? = null,
        val postalCode: MgoString? = null,
        val type: MgoCode_Of_string? = null
    ) {

        init {
            require(_profile == cg_str0) { "_profile not constant value $cg_str0 - $_profile" }
        }

    }

    @Serializable
    data class Country(
        val countryCode: MgoCodeableConcept? = null
    )

    @Serializable
    data class Line(
        val additionalInformation: MgoString? = null,
        val streetName: MgoString? = null,
        val houseNumberLetter: MgoString? = null,
        val countryCode: MgoString? = null,
        val houseNumber: MgoString? = null,
        val houseNumberAddition: MgoString? = null,
        val houseNumberIndiciation: MgoString? = null
    )

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/nl-core-AddressInformation"
        private const val cg_str1 = "http://nictiz.nl/fhir/StructureDefinition/nl-core-HealthProfessional-Practitioner"
        private const val cg_str2 = "R4"
    }

}
