@file:Suppress("ktlint")

/*
 * R4NlCoreContactInformationEmailAddresses.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.hcimParser.uiSchema.models

import kotlinx.serialization.Serializable

@Serializable
data class R4NlCoreContactInformationEmailAddresses(
    val _profile: String = "http://nictiz.nl/fhir/StructureDefinition/zib-ContactInformationEmailAddresses",
    val use: MgoCode? = null,
    val value: MgoString? = null
) {

    init {
        require(_profile == cg_str0) { "_profile not constant value $cg_str0 - $_profile" }
    }

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/zib-ContactInformationEmailAddresses"
    }

}
