@file:Suppress("ktlint")

/*
 * R4NlCoreVaccinationEvent.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.hcimParser.uiSchema.models

import kotlinx.serialization.Serializable

@Serializable
data class R4NlCoreVaccinationEvent(
    val note: List<MgoAnnotation>? = null,
    val identifier: List<MgoIdentifier>? = null,
    val performer: List<Performer>? = null,
    val doseQuantity: MgoQuantity? = null,
    val pharmaceuticalProduct: ExtensionValue_Of_MgoReference? = null,
    val profile: String = "http://nictiz.nl/fhir/StructureDefinition/nl-core-Vaccination-event",
    val referenceId: String,
    val route: MgoCodeableConcept? = null,
    val patient: MgoReference? = null,
    val fhirVersion: String = "R4",
    val protocolApplied: List<ProtocolApplied>? = null,
    val location: MgoReference? = null,
    val occurrenceDateTime: MgoDateTime? = null,
    val occurrenceString: MgoString? = null,
    val reasonCode: ReasonCode,
    val id: String? = null,
    val vaccineCode: MgoCodeableConcept? = null,
    val status: MgoString? = null,
    val resourceType: String
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str1) { "fhirVersion not constant value $cg_str1 - $fhirVersion" }
    }

    @Serializable
    data class Performer(
        val administrator: Administrator
    )

    @Serializable
    data class Administrator(
        val actor: MgoReference? = null
    )

    @Serializable
    data class ProtocolApplied(
        val targetDisease: TargetDisease
    )

    @Serializable
    data class TargetDisease(
        val targetDisease: List<MgoCodeableConcept>? = null
    )

    @Serializable
    data class ReasonCode(
        val vaccinationMotive: List<MgoCodeableConcept>? = null,
        val vaccinationIndication: List<MgoCodeableConcept>? = null
    )

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/nl-core-Vaccination-event"
        private const val cg_str1 = "R4"
    }

}
