@file:Suppress("ktlint")

/*
 * ZibAllergyIntolerance.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.hcimParser.uiSchema.models

import kotlinx.serialization.Serializable

@Serializable
data class ZibAllergyIntolerance(
    val identifier: List<MgoIdentifier>? = null,
    val note: List<MgoAnnotation>? = null,
    val recorder: MgoReference? = null,
    val code: MgoCodeableConcept? = null,
    val reaction: List<Reaction>? = null,
    val verificationStatus: MgoCode_Of_entered_in_error_unconfirmed_confirmed_refuted? = null,
    val profile: String = "http://nictiz.nl/fhir/StructureDefinition/zib-AllergyIntolerance",
    val criticality: Criticality,
    val source: MgoReference? = null,
    val onsetDateTime: MgoDateTime? = null,
    val clinicalStatus: ClinicalStatus,
    val referenceId: String,
    val patient: MgoReference? = null,
    val lastOccurrence: MgoDateTime? = null,
    val fhirVersion: String = "R3",
    val id: String? = null,
    val category: List<Category>? = null,
    val resourceType: String
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str1) { "fhirVersion not constant value $cg_str1 - $fhirVersion" }
    }

    @Serializable
    data class Reaction(
        val severity: Severity,
        val manifestation: List<MgoCodeableConcept>? = null,
        val substance: MgoCodeableConcept? = null,
        val description: MgoString? = null,
        val onset: MgoDateTime? = null,
        val exposureRoute: MgoCodeableConcept? = null
    )

    @Serializable
    data class Severity(
        val severityCodelist: List<ExtensionValue_Of_MgoCodeableConcept>
    )

    @Serializable
    data class Criticality(
        val criticalExtentCodelist: ExtensionValue_Of_MgoCodeableConcept? = null
    )

    @Serializable
    data class ClinicalStatus(
        val allergieStatusCodelijst: ExtensionValue_Of_MgoCodeableConcept? = null
    )

    @Serializable
    data class Category(
        val allergieCategorieCodelijst: ExtensionValue_Of_MgoCodeableConcept? = null
    )

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/zib-AllergyIntolerance"
        private const val cg_str1 = "R3"
    }

}
