@file:Suppress("ktlint")

/*
 * ZibAdministrationSchedule.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.hcimParser.uiSchema.models

import kotlinx.serialization.Serializable

@Serializable
data class ZibAdministrationSchedule(
    val _profile: String = "http://nictiz.nl/fhir/StructureDefinition/zib-AdministrationSchedule",
    val repeat: Repeat
) {

    init {
        require(_profile == cg_str0) { "_profile not constant value $cg_str0 - $_profile" }
    }

    @Serializable
    data class Repeat(
        val boundsDuration: MgoDuration? = null,
        val duration: MgoDecimal? = null,
        val boundsRange: MgoRange? = null,
        val period: MgoDecimal? = null,
        val dayOfWeek: List<MgoCode>? = null,
        val frequencyMax: MgoInteger? = null,
        val boundsPeriod: MgoPeriod? = null,
        val durationUnit: MgoCode? = null,
        val periodUnit: MgoCode? = null,
        val `when`: List<MgoCode>? = null,
        val frequency: MgoInteger? = null,
        val timeOfDay: List<MgoDateTime>? = null
    )

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/zib-AdministrationSchedule"
    }

}
