@file:Suppress("ktlint")

/*
 * ZibBloodPressure.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.hcimParser.uiSchema.models

import kotlinx.serialization.Serializable

@Serializable
data class ZibBloodPressure(
    val identifier: List<MgoIdentifier>? = null,
    val performer: List<MgoReference>? = null,
    val effectivePeriod: MgoPeriod? = null,
    val method: MgoCodeableConcept? = null,
    val subject: MgoReference? = null,
    val profile: String = "http://nictiz.nl/fhir/StructureDefinition/zib-BloodPressure",
    val referenceId: String,
    val bodySite: MgoCodeableConcept? = null,
    val component: Component? = null,
    val effectiveDateTime: MgoDateTime? = null,
    val fhirVersion: String = "R3",
    val comment: MgoString? = null,
    val id: String? = null,
    val resourceType: String
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str1) { "fhirVersion not constant value $cg_str1 - $fhirVersion" }
    }

    @Serializable
    data class Component(
        val averageBloodPressureLoinc: List<AverageBloodPressureLoinc>? = null,
        val systolicBP: List<SystolicBP>? = null,
        val diastolicEndpoint: List<DiastolicEndpoint>? = null,
        val diastolicBP: List<DiastolicBP>? = null,
        val cuffTypeLoinc: List<CuffTypeLoinc>? = null,
        val averageBloodPressureSnomed: List<AverageBloodPressureSnomed>? = null,
        val cuffTypeSnomed: List<CuffTypeSnomed>? = null,
        val positionLoinc: List<PositionLoinc>? = null,
        val positionSnomed: List<PositionSnomed>? = null
    )

    @Serializable
    data class AverageBloodPressureLoinc(
        val valueQuantity: MgoQuantity? = null
    )

    @Serializable
    data class SystolicBP(
        val valueQuantity: MgoQuantity? = null
    )

    @Serializable
    data class DiastolicEndpoint(
        val valueCodeableConcept: MgoCodeableConcept? = null
    )

    @Serializable
    data class DiastolicBP(
        val valueQuantity: MgoQuantity? = null
    )

    @Serializable
    data class CuffTypeLoinc(
        val valueCodeableConcept: MgoCodeableConcept? = null
    )

    @Serializable
    data class AverageBloodPressureSnomed(
        val valueQuantity: MgoQuantity? = null
    )

    @Serializable
    data class CuffTypeSnomed(
        val valueCodeableConcept: MgoCodeableConcept? = null
    )

    @Serializable
    data class PositionLoinc(
        val valueCodeableConcept: MgoCodeableConcept? = null
    )

    @Serializable
    data class PositionSnomed(
        val valueCodeableConcept: MgoCodeableConcept? = null
    )

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/zib-BloodPressure"
        private const val cg_str1 = "R3"
    }

}
