@file:Suppress("ktlint")

/*
 * ZibFamilySituation.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.hcimParser.uiSchema.models

import kotlinx.serialization.Serializable

@Serializable
data class ZibFamilySituation(
    val identifier: List<MgoIdentifier>? = null,
    val performer: List<MgoReference>? = null,
    val effectivePeriod: MgoPeriod? = null,
    val subject: MgoReference? = null,
    val profile: String = "http://nictiz.nl/fhir/StructureDefinition/zib-FamilySituation",
    val referenceId: String,
    val component: Component,
    val children: List<Children>? = null,
    val effectiveDateTime: MgoDateTime? = null,
    val fhirVersion: String = "R3",
    val comment: MgoString? = null,
    val id: String? = null,
    val resourceType: String
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str1) { "fhirVersion not constant value $cg_str1 - $fhirVersion" }
    }

    @Serializable
    data class Component(
        val careResponsibility: List<CareResponsibility>? = null,
        val numberOfChildren: List<NumberOfChildren>? = null,
        val familyComposition: List<FamilyComposition>? = null,
        val numberOfChildrenLivingAtHome: List<NumberOfChildrenLivingAtHome>? = null
    )

    @Serializable
    data class CareResponsibility(
        val valueString: MgoString? = null
    )

    @Serializable
    data class NumberOfChildren(
        val valueQuantity: MgoQuantity? = null
    )

    @Serializable
    data class FamilyComposition(
        val valueCodeableConcept: MgoCodeableConcept? = null
    )

    @Serializable
    data class NumberOfChildrenLivingAtHome(
        val valueQuantity: MgoQuantity? = null
    )

    @Serializable
    data class Children(
        val dateTime: MgoDateTime? = null,
        val livingAtHome: ExtensionValue_Of_MgoBoolean? = null
    )

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/zib-FamilySituation"
        private const val cg_str1 = "R3"
    }

}
