@file:Suppress("ktlint")

/*
 * ZibHelpFromOthers.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.hcimParser.uiSchema.models

import kotlinx.serialization.Serializable

@Serializable
data class ZibHelpFromOthers(
    val identifier: List<MgoIdentifier>? = null,
    val period: MgoPeriod? = null,
    val activity: List<Activity>? = null,
    val subject: MgoReference? = null,
    val profile: String = "http://nictiz.nl/fhir/StructureDefinition/zib-HelpFromOthers",
    val fhirVersion: String = "R3",
    val id: String? = null,
    val referenceId: String,
    val resourceType: String
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str1) { "fhirVersion not constant value $cg_str1 - $fhirVersion" }
    }

    @Serializable
    data class Activity(
        val detail: Detail
    )

    @Serializable
    data class Detail(
        val scheduledString: MgoString? = null,
        val code: MgoString? = null,
        val performer: List<MgoReference>? = null,
        val description: MgoString? = null,
        val category: MgoCodeableConcept? = null
    )

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/zib-HelpFromOthers"
        private const val cg_str1 = "R3"
    }

}
