@file:Suppress("ktlint")

/*
 * ZibLaboratoryTestResultSpecimen.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.hcimParser.uiSchema.models

import kotlinx.serialization.Serializable

@Serializable
data class ZibLaboratoryTestResultSpecimen(
    val container: List<Container>? = null,
    val identifier: List<MgoIdentifier>? = null,
    val parent: List<MgoReference>? = null,
    val note: List<MgoAnnotation>? = null,
    val subject: MgoReference? = null,
    val profile: String = "http://nictiz.nl/fhir/StructureDefinition/zib-LaboratoryTestResult-Specimen",
    val collection: Collection,
    val type: MgoCodeableConcept? = null,
    val referenceId: String,
    val receivedTime: MgoDateTime? = null,
    val fhirVersion: String = "R3",
    val id: String? = null,
    val resourceType: String
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str2) { "fhirVersion not constant value $cg_str2 - $fhirVersion" }
    }

    @Serializable
    data class Container(
        val identifier: List<MgoIdentifier>? = null,
        val type: MgoCodeableConcept? = null
    )

    @Serializable
    data class Collection(
        val bodySite: BodySite,
        val quantity: MgoSimpleQuantity? = null,
        val method: MgoCodeableConcept? = null,
        val collectedPeriod: MgoPeriod? = null,
        val collectedDateTime: MgoDateTime? = null
    )

    @Serializable
    data class BodySite(
        val coding: List<MgoCodingProps>? = null,
        val morphology: List<ExtensionValue_Of_MgoCodeableConcept>,
        val _type: String? = null,
        val text: String? = null,
        val laterality: List<ExtensionValue_Of_MgoCodeableConcept>
    ) {

        init {
            if (_type != null)
                require(_type == cg_str1) { "_type not constant value $cg_str1 - $_type" }
        }

    }

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/zib-LaboratoryTestResult-Specimen"
        private const val cg_str1 = "codeableConcept"
        private const val cg_str2 = "R3"
    }

}
