@file:Suppress("ktlint")

/*
 * ZibMedicationAgreement.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.hcimParser.uiSchema.models

import kotlinx.serialization.Serializable

@Serializable
data class ZibMedicationAgreement(
    val requester: MgoReference? = null,
    val identifier: List<MgoIdentifier>? = null,
    val additionalInformation: ExtensionValue_Of_MgoCodeableConcept? = null,
    val note: List<MgoAnnotation>? = null,
    val medicationTreatment: ExtensionValue_Of_MgoIdentifier? = null,
    val authoredOn: MgoDateTime? = null,
    val profile: String = "http://nictiz.nl/fhir/StructureDefinition/zib-MedicationAgreement",
    val reasonReference: List<MgoReference>? = null,
    val stopType: ExtensionValue_Of_MgoCodeableConcept? = null,
    val dossageInstruction: List<DossageInstruction>? = null,
    val referenceId: String,
    val medicationReference: MgoReference? = null,
    val repeatPeriodCyclicalSchedule: ExtensionValue_Of_MgoDuration? = null,
    val periodOfUse: ExtensionValue_Of_MgoPeriod? = null,
    val usageDuration: ExtensionValue_Of_MgoDuration? = null,
    val patient: MgoReference? = null,
    val fhirVersion: String = "R3",
    val reasonCode: List<MgoCodeableConcept>? = null,
    val id: String? = null,
    val resourceType: String
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str2) { "fhirVersion not constant value $cg_str2 - $fhirVersion" }
    }

    @Serializable
    data class DossageInstruction(
        val additionalInstruction: List<MgoCodeableConcept>? = null,
        val rateRatio: MgoRatio? = null,
        val doseQuantity: MgoQuantityProps? = null,
        val timing: ZibAdministrationSchedule,
        val rateQuantity: MgoQuantityProps? = null,
        val sequence: MgoInteger? = null,
        val route: MgoCodeableConcept? = null,
        val rateRange: MgoRange? = null,
        val _profile: String,
        val doseRange: MgoRange? = null,
        val maxDosePerPeriod: MgoRatio? = null,
        val text: MgoString? = null,
        val asNeededCodeableConcept: MgoCodeableConcept? = null
    ) {

        init {
            require(_profile == cg_str1) { "_profile not constant value $cg_str1 - $_profile" }
        }

    }

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/zib-MedicationAgreement"
        private const val cg_str1 = "http://nictiz.nl/fhir/StructureDefinition/zib-InstructionsForUse"
        private const val cg_str2 = "R3"
    }

}
