@file:Suppress("ktlint")

/*
 * ZibMedicalDeviceRequest.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.hcimParser.uiSchema.models

import kotlinx.serialization.Serializable

@Serializable
data class ZibMedicalDeviceRequest(
    val requester: MgoReference? = null,
    val identifier: List<MgoIdentifier>? = null,
    val subject: MgoReference? = null,
    val profile: String = "http://nictiz.nl/fhir/StructureDefinition/zib-MedicalDeviceRequest",
    val occurrenceTiming: MgoTiming? = null,
    val performerType: PerformerType,
    val referenceId: String,
    val codeReference: MgoReference? = null,
    val occurrencePeriod: MgoPeriod? = null,
    val fhirVersion: String = "R3",
    val occurrenceDateTime: MgoDateTime? = null,
    val id: String? = null,
    val codeCodeableConcept: MgoCodeableConcept? = null,
    val status: Status,
    val resourceType: String
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str1) { "fhirVersion not constant value $cg_str1 - $fhirVersion" }
    }

    @Serializable
    data class PerformerType(
        val healthProfessionalRole: List<MgoCoding>? = null
    )

    @Serializable
    data class Status(
        val orderStatus: ExtensionValue_Of_MgoCodeableConcept? = null
    )

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/zib-MedicalDeviceRequest"
        private const val cg_str1 = "R3"
    }

}
