@file:Suppress("ktlint")

/*
 * ZibNutritionAdvice.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.hcimParser.uiSchema.models

import kotlinx.serialization.Serializable

@Serializable
data class ZibNutritionAdvice(
    val dateTime: MgoDateTime? = null,
    val identifier: List<MgoIdentifier>? = null,
    val oralDiet: OralDiet,
    val patient: MgoReference? = null,
    val orderer: MgoReference? = null,
    val profile: String = "http://nictiz.nl/fhir/StructureDefinition/zib-NutritionAdvice",
    val fhirVersion: String = "R3",
    val comment: ExtensionValue_Of_MgoString? = null,
    val id: String? = null,
    val referenceId: String,
    val resourceType: String
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str1) { "fhirVersion not constant value $cg_str1 - $fhirVersion" }
    }

    @Serializable
    data class OralDiet(
        val texture: List<Texture>? = null,
        val fluidConsistencyType: List<MgoCodeableConcept>? = null,
        val type: List<MgoCodeableConcept>? = null
    )

    @Serializable
    data class Texture(
        val foodType: MgoCodeableConcept? = null,
        val modifier: MgoCodeableConcept? = null
    )

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/zib-NutritionAdvice"
        private const val cg_str1 = "R3"
    }

}
