@file:Suppress("ktlint")

/*
 * ZibProblem.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.hcimParser.uiSchema.models

import kotlinx.serialization.Serializable

@Serializable
data class ZibProblem(
    val identifier: List<MgoIdentifier>? = null,
    val note: List<MgoAnnotation>? = null,
    val code: MgoCodeableConcept? = null,
    val verificationStatus: VerificationStatus,
    val subject: MgoReference? = null,
    val abatementDateTime: MgoDateTime? = null,
    val profile: String = "http://nictiz.nl/fhir/StructureDefinition/zib-Problem",
    val onsetDateTime: MgoDateTime? = null,
    val clinicalStatus: ClinicalStatus,
    val referenceId: String,
    val bodySite: List<BodySite>? = null,
    val asserter: MgoReference? = null,
    val fhirVersion: String = "R3",
    val id: String? = null,
    val category: List<MgoCodeableConcept>? = null,
    val resourceType: String
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str2) { "fhirVersion not constant value $cg_str2 - $fhirVersion" }
    }

    @Serializable
    data class VerificationStatus(
        val verificatieStatusCodelijst: ExtensionValue_Of_MgoCodeableConcept? = null
    )

    @Serializable
    data class ClinicalStatus(
        val problemStatusCodelist: ExtensionValue_Of_MgoCodeableConcept? = null
    )

    @Serializable
    data class BodySite(
        val coding: List<MgoCodingProps>,
        val _type: String,
        val text: String? = null,
        val laterality: ExtensionValue_Of_MgoCodeableConcept? = null
    ) {

        init {
            require(_type == cg_str1) { "_type not constant value $cg_str1 - $_type" }
        }

    }

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/zib-Problem"
        private const val cg_str1 = "codeableConcept"
        private const val cg_str2 = "R3"
    }

}
