@file:Suppress("ktlint")

/*
 * ZibParticipationInSociety.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.hcimParser.uiSchema.models

import kotlinx.serialization.Serializable

@Serializable
data class ZibParticipationInSociety(
    val identifier: List<MgoIdentifier>? = null,
    val component: Component,
    val performer: List<MgoReference>? = null,
    val effectivePeriod: MgoPeriod? = null,
    val effectiveDateTime: MgoDateTime? = null,
    val subject: MgoReference? = null,
    val profile: String = "http://nictiz.nl/fhir/StructureDefinition/zib-ParticipationInSociety",
    val fhirVersion: String = "R3",
    val comment: MgoString? = null,
    val id: String? = null,
    val referenceId: String,
    val resourceType: String
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str1) { "fhirVersion not constant value $cg_str1 - $fhirVersion" }
    }

    @Serializable
    data class Component(
        val workSituation: List<WorkSituation>? = null,
        val socialNetwork: List<SocialNetwork>? = null,
        val hobby: List<Hobby>? = null
    )

    @Serializable
    data class WorkSituation(
        val valueString: MgoString? = null
    )

    @Serializable
    data class SocialNetwork(
        val valueString: MgoString? = null
    )

    @Serializable
    data class Hobby(
        val valueString: MgoString? = null
    )

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/zib-ParticipationInSociety"
        private const val cg_str1 = "R3"
    }

}
