@file:Suppress("ktlint")

/*
 * ZibTextResult.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.hcimParser.uiSchema.models

import kotlinx.serialization.Serializable

@Serializable
data class ZibTextResult(
    val identifier: List<MgoIdentifier>? = null,
    val performer: List<Performer>? = null,
    val code: MgoCodeableConcept? = null,
    val effectivePeriod: MgoPeriod? = null,
    val subject: MgoReference? = null,
    val profile: String = "http://nictiz.nl/fhir/StructureDefinition/zib-TextResult",
    val referenceId: String,
    val conclusion: MgoString? = null,
    val effectiveDateTime: MgoDateTime? = null,
    val fhirVersion: String = "R3",
    val id: String? = null,
    val status: ExtensionValue_Of_MgoCodeableConcept? = null,
    val resourceType: String
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str1) { "fhirVersion not constant value $cg_str1 - $fhirVersion" }
    }

    @Serializable
    data class Performer(
        val actor: MgoReference? = null,
        val role: Role
    )

    @Serializable
    data class Role(
        val healthProfessionalRole: MgoCodeableConcept? = null
    )

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/zib-TextResult"
        private const val cg_str1 = "R3"
    }

}
