@file:Suppress("ktlint")

/*
 * ZibTreatmentObjective.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.hcimParser.uiSchema.models

import kotlinx.serialization.Serializable

@Serializable
data class ZibTreatmentObjective(
    val identifier: List<MgoIdentifier>? = null,
    val expressedBy: MgoReference? = null,
    val addresses: List<MgoReference>? = null,
    val subject: MgoReference? = null,
    val profile: String = "http://nictiz.nl/fhir/StructureDefinition/zib-TreatmentObjective",
    val fhirVersion: String = "R3",
    val description: MgoCodeableConcept? = null,
    val id: String? = null,
    val referenceId: String,
    val target: Target,
    val resourceType: String
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str1) { "fhirVersion not constant value $cg_str1 - $fhirVersion" }
    }

    @Serializable
    data class Target(
        val detailRange: MgoRange? = null,
        val measure: MgoCodeableConcept? = null,
        val detailQuantity: MgoQuantity? = null,
        val detailCodeableConcept: MgoCodeableConcept? = null
    )

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/zib-TreatmentObjective"
        private const val cg_str1 = "R3"
    }

}
