@file:Suppress("ktlint")

/*
 * ZibTreatmentDirective.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.hcimParser.uiSchema.models

import kotlinx.serialization.Serializable

@Serializable
data class ZibTreatmentDirective(
    val dateTime: MgoDateTime? = null,
    val sourceReference: MgoReference? = null,
    val identifier: MgoIdentifier? = null,
    val treatment: ExtensionValue_Of_MgoCodeableConcept? = null,
    val period: MgoPeriod? = null,
    val sourceIdentifier: MgoIdentifier? = null,
    val profile: String = "http://nictiz.nl/fhir/StructureDefinition/zib-TreatmentDirective",
    val sourceAttachment: MgoAttachment? = null,
    val exceptRestrictions: List<ExceptRestriction>? = null,
    val additionalSources: AdditionalSources? = null,
    val referenceId: String,
    val consentingParty: List<MgoReference>? = null,
    val patient: MgoReference? = null,
    val fhirVersion: String = "R3",
    val treatmentPermitted: ExtensionValue_Of_MgoCodeableConcept? = null,
    val comment: ExtensionValue_Of_MgoString? = null,
    val id: String? = null,
    val verification: ExtensionValue_Of_structure_0_22151697474263576? = null,
    val resourceType: String
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str2) { "fhirVersion not constant value $cg_str2 - $fhirVersion" }
    }

    @Serializable
    data class ExceptRestriction(
        val _type: String,
        val value: String,
        val _ext: Boolean
    ) {

        init {
            require(_type == cg_str1) { "_type not constant value $cg_str1 - $_type" }
        }

    }

    @Serializable
    data class AdditionalSources(
        val valueIdentifier: MgoIdentifier? = null,
        val valueAttachment: MgoAttachment? = null,
        val valueReference: MgoReference? = null,
        val _ext: Boolean
    )

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/zib-TreatmentDirective"
        private const val cg_str1 = "string"
        private const val cg_str2 = "R3"
    }

}
