@file:Suppress("ktlint")

/*
 * ZibVaccination.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.hcimParser.uiSchema.models

import kotlinx.serialization.Serializable

@Serializable
data class ZibVaccination(
    val date: MgoDate? = null,
    val identifier: List<MgoIdentifier>? = null,
    val note: List<MgoAnnotation>? = null,
    val practitioner: List<Practitioner>? = null,
    val doseQuantity: MgoQuantity? = null,
    val profile: String = "http://nictiz.nl/fhir/StructureDefinition/zib-Vaccination",
    val referenceId: String,
    val patient: MgoReference? = null,
    val fhirVersion: String = "R3",
    val reportOrigin: MgoCodeableConcept? = null,
    val id: String? = null,
    val vaccineCode: MgoCodeableConcept? = null,
    val resourceType: String
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str1) { "fhirVersion not constant value $cg_str1 - $fhirVersion" }
    }

    @Serializable
    data class Practitioner(
        val actor: MgoReference? = null,
        val role: Role
    )

    @Serializable
    data class Role(
        val healthProfessionalRole: MgoCodeableConcept? = null
    )

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/zib-Vaccination"
        private const val cg_str1 = "R3"
    }

}
