@file:Suppress("ktlint")

/*
 * Attachment.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlin.Double

import kotlinx.serialization.Serializable

@Serializable
data class Attachment(
    val contentType: String? = null,
    val language: String? = null,
    val data: String? = null,
    val url: String? = null,
    val size: Double? = null,
    val hash: String? = null,
    val title: String? = null,
    val creation: String? = null
)
