@file:Suppress("ktlint")

/*
 * DownloadLink.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models


import kotlinx.serialization.SerialName

import kotlinx.serialization.Serializable

@Serializable
@SerialName("DOWNLOAD_LINK")
                data class DownloadLink(
    val label: String,
    val type: String = "DOWNLOAD_LINK",
    val url: String? = null
) : UiElement {

    init {
        require(type == cg_str0) { "type not constant value $cg_str0 - $type" }
    }

    companion object {
        private const val cg_str0 = "DOWNLOAD_LINK"
    }

}
