@file:Suppress("ktlint")

/*
 * EAfspraakAppointment.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class EAfspraakAppointment(
    val specialty: List<MgoCodeableConcept>? = null,
    val profile: String = "http://nictiz.nl/fhir/StructureDefinition/eAfspraak-Appointment",
    val fhirVersion: String = "R3",
    val start: MgoDateTime? = null,
    val description: MgoString? = null,
    val end: MgoDateTime? = null,
    val id: String? = null,
    val participant: List<Participant>? = null,
    val referenceId: String,
    val status: MgoString? = null,
    val resourceType: String
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str1) { "fhirVersion not constant value $cg_str1 - $fhirVersion" }
    }

    @Serializable
    data class Participant(
        val actor: MgoReference? = null
    )

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/eAfspraak-Appointment"
        private const val cg_str1 = "R3"
    }

}
