@file:Suppress("ktlint")

/*
 * ExtensionValue_Of_structure_0_04577354127746314.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class ExtensionValue_Of_structure_0_04577354127746314(
    val period: ExtensionValue_Of_MgoPeriod? = null,
    val code: ExtensionValue_Of_MgoCodeableConcept? = null,
    val _ext: Boolean
)
