@file:Suppress("ktlint")

/*
 * GpDiagnosticResult.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class GpDiagnosticResult(
    val valueBoolean: MgoBoolean? = null,
    val valueTime: MgoTime? = null,
    val code: MgoCodeableConcept? = null,
    val valueRange: MgoRange? = null,
    val subject: MgoReference? = null,
    val referenceId: String,
    val valueCodeableConcept: MgoCodeableConcept? = null,
    val valueRatio: MgoRatio? = null,
    val valueAttachment: MgoAttachment? = null,
    val related: List<Related>? = null,
    val fhirVersion: String = "R3",
    val valueDateTime: MgoDateTime? = null,
    val episodeOfCare: List<ExtensionValue_Of_MgoReference>,
    val id: String? = null,
    val valueQuantity: MgoQuantity? = null,
    val identifier: List<MgoIdentifier>? = null,
    val performer: List<MgoReference>? = null,
    val method: MgoCodeableConcept? = null,
    val effectivePeriod: MgoPeriod? = null,
    val profile: String = "http://nictiz.nl/fhir/StructureDefinition/gp-DiagnosticResult",
    val bodySite: MgoCodeableConcept? = null,
    val valueString: MgoString? = null,
    val effectiveDateTime: MgoDateTime? = null,
    val valuePeriod: MgoPeriod? = null,
    val valueSampledData: MgoSampledData? = null,
    val comment: MgoString? = null,
    val status: Status,
    val resourceType: String
) {

    init {
        require(fhirVersion == cg_str0) { "fhirVersion not constant value $cg_str0 - $fhirVersion" }
        require(profile == cg_str1) { "profile not constant value $cg_str1 - $profile" }
    }

    @Serializable
    data class Related(
        val type: MgoCode_Of_has_member_derived_from_sequel_to_replaces_qualified_by_interfered_by? = null,
        val target: MgoReference? = null
    )

    @Serializable
    data class Status(
        val resultStatusCodelist: ExtensionValue_Of_MgoCodeableConcept? = null
    )

    companion object {
        private const val cg_str0 = "R3"
        private const val cg_str1 = "http://nictiz.nl/fhir/StructureDefinition/gp-DiagnosticResult"
    }

}
