@file:Suppress("ktlint")

/*
 * GpDiagnosticResult.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class GpDiagnosticResult(
    val valueBoolean: Boolean? = null,
    val identifier: List<MgoIdentifier>? = null,
    val performer: List<MgoReference>? = null,
    val code: MgoCodeableConcept? = null,
    val method: MgoCodeableConcept? = null,
    val valueRange: MgoRange? = null,
    val subject: MgoReference? = null,
    val profile: String,
    val referenceId: String,
    val valueCodeableConcept: MgoCodeableConcept? = null,
    val effective: String? = null,
    val valueString: String? = null,
    val valuePeriod: MgoPeriod? = null,
    val fhirVersion: String,
    val context: MgoReference? = null,
    val comment: String? = null,
    val valueDateTime: String? = null,
    val id: String? = null,
    val valueQuantity: MgoQuantity? = null,
    val status: String? = null,
    val resourceType: String? = null
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str1) { "fhirVersion not constant value $cg_str1 - $fhirVersion" }
    }

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/gp-DiagnosticResult"
        private const val cg_str1 = "R3"
    }

}
