@file:Suppress("ktlint")

/*
 * GpEncounter.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class GpEncounter(
    val reason: List<MgoCodeableConcept>? = null,
    val period: MgoPeriod? = null,
    val profile: String = "http://nictiz.nl/fhir/StructureDefinition/gp-Encounter",
    val fhirVersion: String = "R3",
    val serviceProvider: MgoReference? = null,
    val id: String? = null,
    val `class`: MgoCoding? = null,
    val participant: List<EncounterParticipant>? = null,
    val referenceId: String,
    val resourceType: String
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str1) { "fhirVersion not constant value $cg_str1 - $fhirVersion" }
    }

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/gp-Encounter"
        private const val cg_str1 = "R3"
    }

}
