@file:Suppress("ktlint")

/*
 * GpJournalEntry.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class GpJournalEntry(
    val identifier: List<MgoIdentifier>? = null,
    val code: MgoCodeableConcept? = null,
    val performer: List<MgoReference>? = null,
    val effectivePeriod: MgoPeriod? = null,
    val subject: MgoReference? = null,
    val profile: String = "http://nictiz.nl/fhir/StructureDefinition/gp-JournalEntry",
    val referenceId: String,
    val component: Component? = null,
    val valueString: MgoString? = null,
    val effectiveDateTime: MgoDateTime? = null,
    val fhirVersion: String = "R3",
    val episodeOfCare: List<ExtensionValue_Of_MgoReference>,
    val id: String? = null,
    val resourceType: String
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str1) { "fhirVersion not constant value $cg_str1 - $fhirVersion" }
    }

    @Serializable
    data class Component(
        val ICPC_E: List<ICPC_E>? = null,
        val ICPC_S: List<ICPC_S>? = null
    )

    @Serializable
    data class ICPC_E(
        val valueCodeableConcept: MgoCodeableConcept? = null
    )

    @Serializable
    data class ICPC_S(
        val valueCodeableConcept: MgoCodeableConcept? = null
    )

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/gp-JournalEntry"
        private const val cg_str1 = "R3"
    }

}
