@file:Suppress("ktlint")

/*
 * GpJournalEntry.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class GpJournalEntry(
    val identifier: List<MgoIdentifier>? = null,
    val performer: List<MgoReference>? = null,
    val code: MgoCodeableConcept? = null,
    val effectivePeriod: MgoPeriod? = null,
    val ICPC_S: ICPCS,
    val profile: String,
    val referenceId: String,
    val valueString: String? = null,
    val ICPC_E: ICPCE,
    val effectiveDateTime: String? = null,
    val fhirVersion: String,
    val context: MgoReference? = null,
    val id: String? = null,
    val status: String? = null,
    val resourceType: String? = null
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str1) { "fhirVersion not constant value $cg_str1 - $fhirVersion" }
    }

    @Serializable
    data class ICPCS(
        val valueCodeableConcept: MgoCodeableConcept? = null
    )

    @Serializable
    data class ICPCE(
        val valueCodeableConcept: MgoCodeableConcept? = null
    )

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/gp-JournalEntry"
        private const val cg_str1 = "R3"
    }

}
