@file:Suppress("ktlint")

/*
 * GpLaboratoryResult.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class GpLaboratoryResult(
    val id: String? = null,
    val referenceId: String,
    val resourceType: String? = null,
    val profile: String,
    val fhirVersion: String,
    val status: String? = null,
    val referenceRange: List<ReferenceRange>? = null,
    val interpretation: MgoCodeableConcept? = null,
    val specimen: MgoReference? = null,
    val comment: String? = null,
    val laboratoryTestResultCode: List<MgoCodeableConcept>? = null,
    val resultType: List<MgoCodeableConcept>? = null,
    val related: List<Related>? = null,
    val basedOn: List<MgoReference>? = null,
    val performer: List<MgoReference>? = null,
    val valueQuantity: MgoQuantity? = null,
    val valueCodeableConcept: MgoCodeableConcept? = null,
    val valueString: String? = null,
    val valueBoolean: Boolean? = null,
    val valueRange: MgoRange? = null,
    val valueRatio: MgoRatio? = null,
    val valueDateTime: String? = null,
    val valuePeriod: MgoPeriod? = null,
    val effectivePeriod: MgoPeriod? = null,
    val effectiveDateTime: String? = null,
    val identifier: List<MgoIdentifier>? = null,
    val subject: MgoReference? = null,
    val context: MgoReference? = null,
    val code: MgoCodeableConcept? = null,
    val method: MgoCodeableConcept? = null
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str1) { "fhirVersion not constant value $cg_str1 - $fhirVersion" }
        if (status != null)
            require(status in cg_array2) { "status not in enumerated values - $status" }
    }

    @Serializable
    data class ReferenceRange(
        val low: MgoQuantity? = null,
        val high: MgoQuantity? = null,
        val type: MgoCodeableConcept? = null,
        val appliesTo: List<MgoCodeableConcept>? = null,
        val age: MgoRange? = null
    )

    @Serializable
    data class Related(
        val target: MgoReference? = null
    )

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/gp-LaboratoryResult"
        private const val cg_str1 = "R3"
        private val cg_array2 = setOf(
            "registered",
            "preliminary",
            "final",
            "amended",
            "corrected",
            "cancelled",
            "entered-in-error",
            "unknown"
        )
    }

}
