@file:Suppress("ktlint")

/*
 * GpLaboratoryResult.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class GpLaboratoryResult(
    val valueBoolean: MgoBoolean? = null,
    val code: MgoCodeableConcept? = null,
    val valueRange: MgoRange? = null,
    val subject: MgoReference? = null,
    val referenceId: String,
    val valueCodeableConcept: MgoCodeableConcept? = null,
    val valueRatio: MgoRatio? = null,
    val related: List<Related>? = null,
    val fhirVersion: String = "R3",
    val specimen: MgoReference? = null,
    val context: MgoReference? = null,
    val valueDateTime: MgoDateTime? = null,
    val id: String? = null,
    val resultType: List<MgoCodeableConcept>? = null,
    val basedOn: List<MgoReference>? = null,
    val valueQuantity: MgoQuantity? = null,
    val identifier: List<MgoIdentifier>? = null,
    val performer: List<MgoReference>? = null,
    val effectivePeriod: MgoPeriod? = null,
    val method: MgoCodeableConcept? = null,
    val profile: String = "http://nictiz.nl/fhir/StructureDefinition/gp-LaboratoryResult",
    val referenceRange: List<ReferenceRange>? = null,
    val laboratoryTestResultCode: List<MgoCodeableConcept>? = null,
    val valueString: MgoString? = null,
    val interpretation: MgoCodeableConcept? = null,
    val effectiveDateTime: MgoDateTime? = null,
    val valuePeriod: MgoPeriod? = null,
    val comment: MgoString? = null,
    val resourceType: String,
    val status: GpLaboratoryResultStatus? = null
) {

    init {
        require(fhirVersion == cg_str0) { "fhirVersion not constant value $cg_str0 - $fhirVersion" }
        require(profile == cg_str1) { "profile not constant value $cg_str1 - $profile" }
    }

    @Serializable
    data class Related(
        val target: MgoReference? = null
    )

    @Serializable
    data class ReferenceRange(
        val high: MgoQuantity? = null,
        val low: MgoQuantity? = null,
        val appliesTo: List<MgoCodeableConcept>? = null,
        val type: MgoCodeableConcept? = null,
        val age: MgoRange? = null
    )

    companion object {
        private const val cg_str0 = "R3"
        private const val cg_str1 = "http://nictiz.nl/fhir/StructureDefinition/gp-LaboratoryResult"
    }

}
