@file:Suppress("ktlint")

/*
 * IheMhdMinimalDocumentReference.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class IheMhdMinimalDocumentReference(
    val indexed: String? = null,
    val subject: MgoReference? = null,
    val author: List<MgoReference>? = null,
    val securityLabel: List<MgoCodeableConcept>? = null,
    val profile: String = "http://nictiz.nl/fhir/StructureDefinition/IHE.MHD.Minimal.DocumentReference",
    val masterIdentifier: MgoIdentifier? = null,
    val type: MgoCodeableConcept? = null,
    val content: Content,
    val referenceId: String,
    val fhirVersion: String = "R3",
    val id: String? = null,
    val `class`: MgoCodeableConcept? = null,
    val status: String? = null,
    val resourceType: String? = null
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str1) { "fhirVersion not constant value $cg_str1 - $fhirVersion" }
        if (status != null)
            require(status in cg_array2) { "status not in enumerated values - $status" }
    }

    @Serializable
    data class Content(
        val attachment: Attachment? = null
    )

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/IHE.MHD.Minimal.DocumentReference"
        private const val cg_str1 = "R3"
        private val cg_array2 = setOf(
            "entered-in-error",
            "current",
            "superseded"
        )
    }

}
