@file:Suppress("ktlint")

/*
 * MgoAttachment.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlin.Double

import kotlinx.serialization.Serializable

@Serializable
data class MgoAttachment(
    val data: String? = null,
    val size: Double? = null,
    val _type: String = "attachment",
    val language: String? = null,
    val title: String? = null,
    val contentType: String? = null,
    val url: String? = null,
    val hash: String? = null,
    val creation: String? = null
) {

    init {
        require(_type == cg_str0) { "_type not constant value $cg_str0 - $_type" }
    }

    companion object {
        private const val cg_str0 = "attachment"
    }

}
