@file:Suppress("ktlint")

/*
 * MgoElementMeta_Of_http___fhir_nl_fhir_StructureDefinition_nl_core_contactpoint.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class MgoElementMeta_Of_http___fhir_nl_fhir_StructureDefinition_nl_core_contactpoint(
    val _profile: String = "http://fhir.nl/fhir/StructureDefinition/nl-core-contactpoint"
) {

    init {
        require(_profile == cg_str0) { "_profile not constant value $cg_str0 - $_profile" }
    }

    companion object {
        private const val cg_str0 = "http://fhir.nl/fhir/StructureDefinition/nl-core-contactpoint"
    }

}
