@file:Suppress("ktlint")

/*
 * MgoIdentifier.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class MgoIdentifier(
    val system: String? = null,
    val use: String? = null,
    val _type: String = "identifier",
    val type: Type? = null,
    val value: String? = null
) {

    init {
        require(_type == cg_str0) { "_type not constant value $cg_str0 - $_type" }
    }

    @Serializable
    data class Type(
        val coding: List<MgoCodingProps>,
        val text: String? = null
    )

    companion object {
        private const val cg_str0 = "identifier"
    }

}
