@file:Suppress("ktlint")

/*
 * MgoSampledData.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class MgoSampledData(
    val period: MgoDecimal,
    val data: MgoString? = null,
    val origin: MgoSimpleQuantity? = null,
    val _type: String = "sampledData",
    val upperLimit: MgoDecimal? = null,
    val lowerLimit: MgoDecimal? = null,
    val factor: MgoDecimal? = null,
    val dimensions: MgoPositiveInt? = null
) {

    init {
        require(_type == cg_str0) { "_type not constant value $cg_str0 - $_type" }
    }

    companion object {
        private const val cg_str0 = "sampledData"
    }

}
