@file:Suppress("ktlint")

/*
 * MgoTiming.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class MgoTiming(
    val code: MgoCodeableConcept? = null,
    val repeat: Repeat,
    val _type: String = "timing",
    val event: List<MgoDateTime>? = null
) {

    init {
        require(_type == cg_str0) { "_type not constant value $cg_str0 - $_type" }
    }

    @Serializable
    data class Repeat(
        val boundsRange: MgoRange? = null,
        val period: MgoDecimal? = null,
        val offset: MgoUnsignedInt? = null,
        val frequencyMax: MgoInteger? = null,
        val countMax: MgoInteger? = null,
        val periodMax: MgoDecimal? = null,
        val count: MgoInteger? = null,
        val periodUnit: MgoString? = null,
        val `when`: List<MgoString>? = null,
        val frequency: MgoInteger? = null,
        val boundsDuration: MgoDuration? = null,
        val duration: MgoDecimal? = null,
        val durationMax: MgoDecimal? = null,
        val dayOfWeek: List<MgoString>? = null,
        val boundsPeriod: MgoPeriod? = null,
        val durationUnit: MgoString? = null,
        val timeOfDay: List<MgoString>? = null
    )

    companion object {
        private const val cg_str0 = "timing"
    }

}
