@file:Suppress("ktlint")

/*
 * MultipleGroupedValues.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models


import kotlinx.serialization.SerialName

import kotlinx.serialization.Serializable

@Serializable
@SerialName("MULTIPLE_GROUPED_VALUES")
                data class MultipleGroupedValues(
    val display: List<List<String>>? = null,
    val label: String,
    val type: String = "MULTIPLE_GROUPED_VALUES"
) : UiElement {

    init {
        require(type == cg_str0) { "type not constant value $cg_str0 - $type" }
    }

    companion object {
        private const val cg_str0 = "MULTIPLE_GROUPED_VALUES"
    }

}
