@file:Suppress("ktlint")

/*
 * NlCoreAddress.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class NlCoreAddress(
    val country: MgoString? = null,
    val _profile: String = "http://fhir.nl/fhir/StructureDefinition/nl-core-address",
    val city: MgoString? = null,
    val addressType: MgoCodeableConcept? = null,
    val use: MgoCode? = null,
    val line: List<Line>? = null,
    val district: MgoString? = null,
    val postalCode: MgoString? = null,
    val official: MgoBoolean? = null,
    val type: MgoCode? = null
) {

    init {
        require(_profile == cg_str0) { "_profile not constant value $cg_str0 - $_profile" }
    }

    @Serializable
    data class Line(
        val streetName: MgoString? = null,
        val buildingNumberSuffix: MgoString? = null,
        val additionalLocator: MgoString? = null,
        val houseNumber: MgoString? = null,
        val unitId: MgoString? = null
    )

    companion object {
        private const val cg_str0 = "http://fhir.nl/fhir/StructureDefinition/nl-core-address"
    }

}
