@file:Suppress("ktlint")

/*
 * NlCoreContactpoint.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class NlCoreContactpoint(
    val period: MgoPeriod? = null,
    val system: MgoCode? = null,
    val use: MgoCode? = null,
    val rank: MgoPositiveInt? = null,
    val value: MgoString? = null
)
