@file:Suppress("ktlint")

/*
 * NlCoreAddress.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class NlCoreAddress(
    val country: MgoString? = null,
    val period: MgoPeriod? = null,
    val city: MgoString? = null,
    val use: MgoCode? = null,
    val line: List<MgoString>? = null,
    val district: MgoString? = null,
    val postalCode: MgoString? = null,
    val text: MgoString? = null,
    val state: MgoString? = null,
    val type: MgoCode? = null
)
