@file:Suppress("ktlint")

/*
 * NlCoreAddress.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class NlCoreAddress(
    val use: String? = null,
    val type: String? = null,
    val text: String? = null,
    val line: List<String>? = null,
    val city: String? = null,
    val district: String? = null,
    val state: String? = null,
    val postalCode: String? = null,
    val country: String? = null,
    val period: MgoPeriod? = null
)
