@file:Suppress("ktlint")

/*
 * NlCoreEpisodeofcare.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlin.Double

import kotlinx.serialization.Serializable

@Serializable
data class NlCoreEpisodeofcare(
    val identifier: List<MgoIdentifier>? = null,
    val period: MgoPeriod? = null,
    val profile: String,
    val diagnosis: List<Diagnosi>? = null,
    val careManager: MgoReference? = null,
    val team: List<MgoReference>? = null,
    val title: String? = null,
    val type: List<MgoCodeableConcept>? = null,
    val referenceId: String,
    val statusHistory: List<StatusHistory>? = null,
    val managingOrganization: MgoReference? = null,
    val referralRequest: List<MgoReference>? = null,
    val patient: MgoReference? = null,
    val fhirVersion: String,
    val id: String? = null,
    val account: List<MgoReference>? = null,
    val dateFirstEncounter: String? = null,
    val status: String? = null,
    val dateLastEncounter: String? = null,
    val resourceType: String? = null
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str1) { "fhirVersion not constant value $cg_str1 - $fhirVersion" }
        if (status != null)
            require(status in cg_array2) { "status not in enumerated values - $status" }
    }

    @Serializable
    data class Diagnosi(
        val condition: MgoReference? = null,
        val role: MgoCodeableConcept? = null,
        val rank: Double? = null
    )

    @Serializable
    data class StatusHistory(
        val period: MgoPeriod? = null,
        val status: String? = null
    )

    companion object {
        private const val cg_str0 = "http://fhir.nl/fhir/StructureDefinition/nl-core-episodeofcare"
        private const val cg_str1 = "R3"
        private val cg_array2 = setOf(
            "active",
            "cancelled",
            "entered-in-error",
            "planned",
            "waitlist",
            "onhold",
            "finished"
        )
    }

}
