@file:Suppress("ktlint")

/*
 * NlCoreObservation.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class NlCoreObservation(
    val identifier: List<MgoIdentifier>? = null,
    val status: String? = null,
    val category: List<MgoCodeableConcept>? = null,
    val subject: MgoReference? = null,
    val context: MgoReference? = null,
    val valueQuantity: MgoQuantity? = null,
    val effectivePeriod: MgoPeriod? = null,
    val dataAbsentReason: MgoCodeableConcept? = null,
    val method: MgoCodeableConcept? = null,
    val bodySite: MgoCodeableConcept? = null,
    val effectiveDateTime: String? = null,
    val comment: String? = null,
    val id: String? = null,
    val referenceId: String,
    val resourceType: String? = null,
    val profile: String,
    val fhirVersion: String
) {

    init {
        if (status != null)
            require(status in cg_array0) { "status not in enumerated values - $status" }
        require(profile == cg_str1) { "profile not constant value $cg_str1 - $profile" }
        require(fhirVersion == cg_str2) { "fhirVersion not constant value $cg_str2 - $fhirVersion" }
    }

    companion object {
        private val cg_array0 = setOf(
            "registered",
            "preliminary",
            "final",
            "amended",
            "corrected",
            "cancelled",
            "entered-in-error",
            "unknown"
        )
        private const val cg_str1 = "http://fhir.nl/fhir/StructureDefinition/nl-core-observation"
        private const val cg_str2 = "R3"
    }

}
