@file:Suppress("ktlint")

/*
 * NlCoreHumanname.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class NlCoreHumanname(
    val given: List<MgoString>? = null,
    val period: MgoPeriod? = null,
    val prefix: List<MgoString>? = null,
    val use: MgoString? = null,
    val text: MgoString? = null,
    val family: MgoString? = null,
    val suffix: List<MgoString>? = null
)
