@file:Suppress("ktlint")

/*
 * NlCoreOrganization.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class NlCoreOrganization(
    val organizationType: List<MgoCodeableConcept>? = null,
    val identifier: List<MgoIdentifier>? = null,
    val address: List<NlCoreAddress>? = null,
    val profile: String,
    val fhirVersion: String,
    val name: String? = null,
    val telecom: List<NlCoreContactpoint>? = null,
    val id: String? = null,
    val departmentSpecialty: List<MgoCodeableConcept>? = null,
    val referenceId: String,
    val resourceType: String? = null
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str1) { "fhirVersion not constant value $cg_str1 - $fhirVersion" }
    }

    companion object {
        private const val cg_str0 = "http://fhir.nl/fhir/StructureDefinition/nl-core-organization"
        private const val cg_str1 = "R3"
    }

}
