@file:Suppress("ktlint")

/*
 * NlCoreEpisodeofcare.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class NlCoreEpisodeofcare(
    val identifier: List<MgoIdentifier>? = null,
    val period: MgoPeriod? = null,
    val profile: String = "http://fhir.nl/fhir/StructureDefinition/nl-core-episodeofcare",
    val diagnosis: List<Diagnosi>? = null,
    val careManager: MgoReference? = null,
    val team: List<MgoReference>? = null,
    val title: MgoString? = null,
    val type: List<MgoCodeableConcept>? = null,
    val referenceId: String,
    val statusHistory: List<StatusHistory>? = null,
    val managingOrganization: MgoReference? = null,
    val referralRequest: List<MgoReference>? = null,
    val patient: MgoReference? = null,
    val fhirVersion: String = "R3",
    val id: String? = null,
    val account: List<MgoReference>? = null,
    val dateFirstEncounter: MgoDateTime? = null,
    val status: NlCoreEpisodeofcareStatus? = null,
    val dateLastEncounter: MgoDateTime? = null,
    val resourceType: String
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str1) { "fhirVersion not constant value $cg_str1 - $fhirVersion" }
    }

    @Serializable
    data class Diagnosi(
        val condition: MgoReference? = null,
        val role: MgoCodeableConcept? = null,
        val rank: MgoPositiveInt? = null
    )

    @Serializable
    data class StatusHistory(
        val period: MgoPeriod? = null,
        val status: MgoCode? = null
    )

    companion object {
        private const val cg_str0 = "http://fhir.nl/fhir/StructureDefinition/nl-core-episodeofcare"
        private const val cg_str1 = "R3"
    }

}
