@file:Suppress("ktlint")

/*
 * NlCorePatient.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class NlCorePatient(
    val identifier: List<MgoIdentifier>? = null,
    val address: List<NlCoreAddress>? = null,
    val deceased: MgoBoolean? = null,
    val gender: NlCorePatientGender? = null,
    val profile: String = "http://fhir.nl/fhir/StructureDefinition/nl-core-patient",
    val link: List<Link>? = null,
    val active: MgoBoolean? = null,
    val photo: List<MgoAttachment>? = null,
    val birthDate: MgoDate? = null,
    val referenceId: String,
    val multipleBirth: MgoBoolean? = null,
    val managingOrganization: MgoReference? = null,
    val multipleBirthInteger: MgoInteger? = null,
    val contact: List<Contact>? = null,
    val deceasedDateTime: MgoDateTime? = null,
    val generalPractitioner: List<MgoReference>? = null,
    val fhirVersion: String = "R3",
    val name: List<NlCoreHumanname>? = null,
    val telecom: List<NlCoreContactpoint>? = null,
    val id: String? = null,
    val communication: List<Communication>? = null,
    val maritalStatus: MgoCodeableConcept? = null,
    val resourceType: String
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str1) { "fhirVersion not constant value $cg_str1 - $fhirVersion" }
    }

    @Serializable
    data class Link(
        val other: MgoReference? = null,
        val type: MgoCode? = null
    )

    @Serializable
    data class Contact(
        val period: MgoPeriod? = null,
        val address: NlCoreAddress,
        val gender: MgoCode? = null,
        val organization: MgoReference? = null,
        val name: NlCoreHumanname,
        val telecom: List<NlCoreContactpoint>,
        val relationship: List<MgoCodeableConcept>
    )

    @Serializable
    data class Communication(
        val language: MgoCodeableConcept? = null,
        val preferred: MgoBoolean? = null
    )

    companion object {
        private const val cg_str0 = "http://fhir.nl/fhir/StructureDefinition/nl-core-patient"
        private const val cg_str1 = "R3"
    }

}
