@file:Suppress("ktlint")

/*
 * NlCoreEpisodeofcare.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class NlCoreEpisodeofcare(
    val identifier: List<MgoIdentifier>? = null,
    val period: MgoPeriod? = null,
    val patient: MgoReference? = null,
    val profile: String = "http://fhir.nl/fhir/StructureDefinition/nl-core-episodeofcare",
    val fhirVersion: String = "R3",
    val id: String? = null,
    val type: List<MgoCodeableConcept>? = null,
    val title: Title? = null,
    val referenceId: String,
    val resourceType: String
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str1) { "fhirVersion not constant value $cg_str1 - $fhirVersion" }
    }

    @Serializable
    data class Title(
        val _type: String,
        val value: String,
        val _ext: Boolean
    ) {

        init {
            require(_type == cg_str2) { "_type not constant value $cg_str2 - $_type" }
        }

    }

    companion object {
        private const val cg_str0 = "http://fhir.nl/fhir/StructureDefinition/nl-core-episodeofcare"
        private const val cg_str1 = "R3"
        private const val cg_str2 = "string"
    }

}
