@file:Suppress("ktlint")

/*
 * NlCorePractitionerRole.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class NlCorePractitionerRole(
    val identifier: List<MgoIdentifier>? = null,
    val specialty: MgoCodeableConcept? = null,
    val organization: MgoReference? = null,
    val profile: String = "http://fhir.nl/fhir/StructureDefinition/nl-core-practitionerrole",
    val fhirVersion: String = "R3",
    val telecom: List<Telecom>? = null,
    val id: String? = null,
    val referenceId: String,
    val resourceType: String
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str1) { "fhirVersion not constant value $cg_str1 - $fhirVersion" }
    }

    @Serializable
    data class Telecom(
        val system: MgoCode_Of_string? = null,
        val _profile: String,
        val use: MgoCode_Of_string? = null,
        val telecomType: MgoCodeableConcept? = null,
        val value: MgoString? = null
    ) {

        init {
            require(_profile == cg_str2) { "_profile not constant value $cg_str2 - $_profile" }
        }

    }

    companion object {
        private const val cg_str0 = "http://fhir.nl/fhir/StructureDefinition/nl-core-practitionerrole"
        private const val cg_str1 = "R3"
        private const val cg_str2 = "http://fhir.nl/fhir/StructureDefinition/nl-core-contactpoint"
    }

}
