@file:Suppress("ktlint")

/*
 * PrimitiveValueType_Of_code__y_n_unk_na.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class PrimitiveValueType_Of_code__y_n_unk_na(
    val _type: String = "code",
    val value: Value
) {

    init {
        require(_type == cg_str0) { "_type not constant value $cg_str0 - $_type" }
    }

    @Serializable
    enum class Value {
        y,
        n,
        unk,
        na
    }

    companion object {
        private const val cg_str0 = "code"
    }

}
