@file:Suppress("ktlint")

/*
 * PrimitiveValueType_Of_instant__InstantDateTimeString.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class PrimitiveValueType_Of_instant__InstantDateTimeString(
    val _type: String = "instant",
    val value: String
) {

    init {
        require(_type == cg_str0) { "_type not constant value $cg_str0 - $_type" }
    }

    companion object {
        private const val cg_str0 = "instant"
    }

}
