@file:Suppress("ktlint")

/*
 * Profiles.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data object Profiles {
    val zibAlcoholUse: String = "http://nictiz.nl/fhir/StructureDefinition/zib-AlcoholUse"
    val zibMedicalDeviceRequest: String = "http://nictiz.nl/fhir/StructureDefinition/zib-MedicalDeviceRequest"
    val zibTreatmentDirective: String = "http://nictiz.nl/fhir/StructureDefinition/zib-TreatmentDirective"
    val zibProblem: String = "http://nictiz.nl/fhir/StructureDefinition/zib-Problem"
    val nlCoreHealthcareProvider: String = "http://nictiz.nl/fhir/StructureDefinition/nl-core-HealthcareProvider"
    val nlCorePatient: String = "http://nictiz.nl/fhir/StructureDefinition/nl-core-Patient"
    val zibBodyHeight: String = "http://nictiz.nl/fhir/StructureDefinition/zib-BodyHeight"
    val zibNutritionAdvice: String = "http://nictiz.nl/fhir/StructureDefinition/zib-NutritionAdvice"
    val nlCoreEpisodeofcare: String = "http://fhir.nl/fhir/StructureDefinition/nl-core-episodeofcare"
    val zibLivingSituation: String = "http://nictiz.nl/fhir/StructureDefinition/zib-LivingSituation"
    val zibPayer: String = "http://nictiz.nl/fhir/StructureDefinition/zib-Payer"
    val nlCorePractitionerrole: String = "http://fhir.nl/fhir/StructureDefinition/nl-core-practitionerrole"
    val zibMedicationUse: String = "http://nictiz.nl/fhir/StructureDefinition/zib-MedicationUse"
    val gpLaboratoryResult: String = "http://nictiz.nl/fhir/StructureDefinition/gp-LaboratoryResult"
    val zibFunctionalOrMentalStatus: String = "http://nictiz.nl/fhir/StructureDefinition/zib-FunctionalOrMentalStatus"
    val nlCorePractitioner: String = "http://fhir.nl/fhir/StructureDefinition/nl-core-practitioner"
    val zibAdvanceDirective: String = "http://nictiz.nl/fhir/StructureDefinition/zib-AdvanceDirective"
    val zibDrugUse: String = "http://nictiz.nl/fhir/StructureDefinition/zib-DrugUse"
    val zibBloodPressure: String = "http://nictiz.nl/fhir/StructureDefinition/zib-BloodPressure"
    val gpEncounter: String = "http://nictiz.nl/fhir/StructureDefinition/gp-Encounter"
    val nlCoreHealthProfessionalPractitionerRole: String = "http://nictiz.nl/fhir/StructureDefinition/nl-core-HealthProfessional-PractitionerRole"
    val zibAdministrationAgreement: String = "http://nictiz.nl/fhir/StructureDefinition/zib-AdministrationAgreement"
    val nlCoreObservation: String = "http://fhir.nl/fhir/StructureDefinition/nl-core-observation"
    val zibLaboratoryTestResultSubstance: String = "http://nictiz.nl/fhir/StructureDefinition/zib-LaboratoryTestResult-Substance"
    val zibMedicationAgreement: String = "http://nictiz.nl/fhir/StructureDefinition/zib-MedicationAgreement"
    val nlCoreHealthcareProviderOrganization: String = "http://nictiz.nl/fhir/StructureDefinition/nl-core-HealthcareProvider-Organization"
    val zibAlert: String = "http://nictiz.nl/fhir/StructureDefinition/zib-Alert"
    val gpDiagnosticResult: String = "http://nictiz.nl/fhir/StructureDefinition/gp-DiagnosticResult"
    val zibEncounter: String = "http://nictiz.nl/fhir/StructureDefinition/zib-Encounter"
    val zibProcedure: String = "http://nictiz.nl/fhir/StructureDefinition/zib-Procedure"
    val zibTobaccoUse: String = "http://nictiz.nl/fhir/StructureDefinition/zib-TobaccoUse"
    val zibAllergyIntolerance: String = "http://nictiz.nl/fhir/StructureDefinition/zib-AllergyIntolerance"
    val zibGeneralMeasurement: String = "http://nictiz.nl/fhir/StructureDefinition/zib-GeneralMeasurement"
    val zibVaccinationRecommendation: String = "http://nictiz.nl/fhir/StructureDefinition/zib-VaccinationRecommendation"
    val nlCorePharmaceuticalProduct: String = "http://nictiz.nl/fhir/StructureDefinition/nl-core-PharmaceuticalProduct"
    val zibProduct: String = "http://nictiz.nl/fhir/StructureDefinition/zib-Product"
    val iHEMHDMinimalDocumentReference: String = "http://nictiz.nl/fhir/StructureDefinition/IHE.MHD.Minimal.DocumentReference"
    val nlCoreVaccinationEvent: String = "http://nictiz.nl/fhir/StructureDefinition/nl-core-Vaccination-event"
    val zibBodyWeight: String = "http://nictiz.nl/fhir/StructureDefinition/zib-BodyWeight"
    val eAfspraakAppointment: String = "http://nictiz.nl/fhir/StructureDefinition/eAfspraak-Appointment"
    val zibLaboratoryTestResultSpecimen: String = "http://nictiz.nl/fhir/StructureDefinition/zib-LaboratoryTestResult-Specimen"
    val gpJournalEntry: String = "http://nictiz.nl/fhir/StructureDefinition/gp-JournalEntry"
    val nlCoreHealthProfessionalPractitioner: String = "http://nictiz.nl/fhir/StructureDefinition/nl-core-HealthProfessional-Practitioner"
    val zibMedicalDevice: String = "http://nictiz.nl/fhir/StructureDefinition/zib-MedicalDevice"
    val zibVaccination: String = "http://nictiz.nl/fhir/StructureDefinition/zib-Vaccination"
    val zibLaboratoryTestResultObservation: String = "http://nictiz.nl/fhir/StructureDefinition/zib-LaboratoryTestResult-Observation"
    val zibLaboratoryTestResultSpecimenIsolate: String = "http://nictiz.nl/fhir/StructureDefinition/zib-LaboratoryTestResult-Specimen-Isolate"
    val zibProcedureRequest: String = "http://nictiz.nl/fhir/StructureDefinition/zib-ProcedureRequest"
    val zibMedicalDeviceProduct: String = "http://nictiz.nl/fhir/StructureDefinition/zib-MedicalDeviceProduct"
    val gpEncounterReport: String = "http://nictiz.nl/fhir/StructureDefinition/gp-EncounterReport"
    val nlCoreOrganization: String = "http://fhir.nl/fhir/StructureDefinition/nl-core-organization"
 } 