@file:Suppress("ktlint")

/*
 * R4NlCoreContactInformationTelephoneNumbers.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class R4NlCoreContactInformationTelephoneNumbers(
    val system: System,
    val _profile: String = "http://nictiz.nl/fhir/StructureDefinition/zib-ContactInformationTelephoneNumbers",
    val use: MgoCode? = null,
    val comment: MgoString? = null,
    val value: MgoString? = null
) {

    init {
        require(_profile == cg_str0) { "_profile not constant value $cg_str0 - $_profile" }
    }

    @Serializable
    data class System(
        val telecomType: MgoCodeableConcept? = null
    )

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/zib-ContactInformationTelephoneNumbers"
    }

}
