@file:Suppress("ktlint")

/*
 * R4NlCoreContactInformationTelephoneNumbers.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class R4NlCoreContactInformationTelephoneNumbers(
    val system: String = "phone",
    val use: MgoCode? = null,
    val telecomType: MgoCodeableConcept? = null,
    val comment: MgoString? = null,
    val value: MgoString? = null
) {

    init {
        require(system == cg_str0) { "system not constant value $cg_str0 - $system" }
    }

    companion object {
        private const val cg_str0 = "phone"
    }

}
