@file:Suppress("ktlint")

/*
 * R4NlCoreNameInformationUse.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class R4NlCoreNameInformationUse(
    val _type: String = "code",
    val value: String = "official"
) {

    init {
        require(_type == cg_str0) { "_type not constant value $cg_str0 - $_type" }
        require(value == cg_str1) { "value not constant value $cg_str1 - $value" }
    }

    companion object {
        private const val cg_str0 = "code"
        private const val cg_str1 = "official"
    }

}
