@file:Suppress("ktlint")

/*
 * R4NlCoreHealthProfessionalPractitioner.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class R4NlCoreHealthProfessionalPractitioner(
    val identifier: List<MgoIdentifier>? = null,
    val telephoneNumbers: List<R4NlCoreContactInformationTelephoneNumbers>? = null,
    val emailAddresses: List<R4NlCoreContactInformationEmailAddresses>? = null,
    val address: List<R4NlCoreAddressInformation>? = null,
    val gender: Gender? = null,
    val birthDate: String? = null,
    val qualification: List<Qualification>? = null,
    val communication: List<MgoCodeableConcept>? = null,
    val id: String? = null,
    val referenceId: String,
    val resourceType: String? = null,
    val profile: String,
    val fhirVersion: String
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str1) { "fhirVersion not constant value $cg_str1 - $fhirVersion" }
    }

    @Serializable
    enum class Gender {
        unknown,
        male,
        female,
        other
    }

    @Serializable
    data class Qualification(
        val identifier: List<MgoIdentifier>? = null,
        val code: MgoCodeableConcept? = null,
        val period: MgoPeriod? = null,
        val issuer: MgoReference? = null
    )

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/nl-core-HealthProfessional-Practitioner"
        private const val cg_str1 = "R4"
    }

}
