@file:Suppress("ktlint")

/*
 * R4NlCoreNameInformation.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class R4NlCoreNameInformation(
    val use: String,
    val text: String? = null,
    val given: List<String>? = null,
    val givenNames: List<String>? = null,
    val givenInitials: List<String>? = null,
    val period: MgoPeriod? = null,
    val family: String? = null,
    val prefix: List<String>? = null,
    val suffix: List<String>? = null,
    val nameUsage: String? = null
) {

    init {
        require(use == cg_str0) { "use not constant value $cg_str0 - $use" }
    }

    companion object {
        private const val cg_str0 = "official"
    }

}
