@file:Suppress("ktlint")

/*
 * R4NlCoreAddressInformation.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class R4NlCoreAddressInformation(
    val country: Country,
    val _profile: String = "http://nictiz.nl/fhir/StructureDefinition/nl-core-AddressInformation",
    val city: MgoString? = null,
    val use: MgoCode? = null,
    val line: List<Line>? = null,
    val district: MgoString? = null,
    val postalCode: MgoString? = null,
    val type: MgoCode? = null
) {

    init {
        require(_profile == cg_str0) { "_profile not constant value $cg_str0 - $_profile" }
    }

    @Serializable
    data class Country(
        val countryCode: MgoCodeableConcept? = null
    )

    @Serializable
    data class Line(
        val additionalInformation: MgoString? = null,
        val streetName: MgoString? = null,
        val houseNumberLetter: MgoString? = null,
        val countryCode: MgoString? = null,
        val houseNumber: MgoString? = null,
        val houseNumberAddition: MgoString? = null,
        val houseNumberIndiciation: MgoString? = null
    )

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/nl-core-AddressInformation"
    }

}
