@file:Suppress("ktlint")

/*
 * R4NlCoreHealthProfessionalPractitionerRole.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class R4NlCoreHealthProfessionalPractitionerRole(
    val speciality: List<MgoCodeableConcept>? = null,
    val emailAddresses: List<R4NlCoreContactInformationEmailAddresses>? = null,
    val practitioner: MgoReference? = null,
    val organization: MgoReference? = null,
    val profile: String = "http://nictiz.nl/fhir/StructureDefinition/nl-core-HealthProfessional-PractitionerRole",
    val fhirVersion: String = "R4",
    val telephoneNumbers: List<R4NlCoreContactInformationTelephoneNumbers>? = null,
    val location: List<MgoReference>? = null,
    val id: String? = null,
    val referenceId: String,
    val resourceType: String
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str1) { "fhirVersion not constant value $cg_str1 - $fhirVersion" }
    }

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/nl-core-HealthProfessional-PractitionerRole"
        private const val cg_str1 = "R4"
    }

}
