@file:Suppress("ktlint")

/*
 * R4NlCorePharmaceuticalProduct.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class R4NlCorePharmaceuticalProduct(
    val description: String? = null,
    val code: MgoCodeableConcept? = null,
    val status: String? = null,
    val manufacturer: MgoReference? = null,
    val form: MgoCodeableConcept? = null,
    val amount: MgoRatio? = null,
    val ingredient: List<Ingredient>? = null,
    val batch: Batch,
    val identifier: List<MgoIdentifier>? = null,
    val name: String? = null,
    val id: String? = null,
    val referenceId: String,
    val resourceType: String? = null,
    val profile: String,
    val fhirVersion: String
) {

    init {
        if (status != null)
            require(status in cg_array0) { "status not in enumerated values - $status" }
        require(profile == cg_str1) { "profile not constant value $cg_str1 - $profile" }
        require(fhirVersion == cg_str2) { "fhirVersion not constant value $cg_str2 - $fhirVersion" }
    }

    @Serializable
    data class Ingredient(
        val itemReference: MgoReference? = null,
        val itemCodeableConcept: MgoCodeableConcept? = null,
        val strength: MgoRatio? = null
    )

    @Serializable
    data class Batch(
        val lotNumber: String? = null,
        val expirationDate: String? = null
    )

    companion object {
        private val cg_array0 = setOf(
            "active",
            "entered-in-error",
            "inactive"
        )
        private const val cg_str1 = "http://nictiz.nl/fhir/StructureDefinition/nl-core-PharmaceuticalProduct"
        private const val cg_str2 = "R4"
    }

}
