@file:Suppress("ktlint")

/*
 * R4NlCoreVaccinationEvent.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlin.Double

import kotlinx.serialization.Serializable

@Serializable
data class R4NlCoreVaccinationEvent(
    val pharmaceuticalProduct: MgoReference? = null,
    val identifier: List<MgoIdentifier>? = null,
    val status: String? = null,
    val vaccineCode: MgoCodeableConcept? = null,
    val patient: MgoReference? = null,
    val occurrenceDateTime: String? = null,
    val location: MgoReference? = null,
    val site: MgoCodeableConcept? = null,
    val route: MgoCodeableConcept? = null,
    val doseQuantity: MgoQuantity? = null,
    val performer: List<MgoReference>? = null,
    val note: List<MgoAnnotation>? = null,
    val vaccinationIndication: List<MgoCodeableConcept>? = null,
    val vaccinationMotive: List<MgoCodeableConcept>? = null,
    val protocolApplied: List<ProtocolApplied>? = null,
    val id: String? = null,
    val referenceId: String,
    val resourceType: String? = null,
    val profile: String,
    val fhirVersion: String
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str1) { "fhirVersion not constant value $cg_str1 - $fhirVersion" }
    }

    @Serializable
    data class ProtocolApplied(
        val authority: MgoReference? = null,
        val targetDisease: List<MgoCodeableConcept>? = null,
        val doseNumberPositiveInt: Double? = null,
        val doseNumberString: String? = null,
        val seriesDosesPositiveInt: Double? = null,
        val seriesDosesString: String? = null
    )

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/nl-core-Vaccination-event"
        private const val cg_str1 = "R4"
    }

}
