@file:Suppress("ktlint")

/*
 * R4NlCoreNameInformationGiven.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class R4NlCoreNameInformationGiven(
    val given: List<MgoString>? = null,
    val period: MgoPeriod? = null,
    val use: R4NlCoreNameInformationGivenUse,
    val text: MgoString? = null
) : R4NlCorePatientName, R4NlCoreHealthProfessionalPractitionerName
