@file:Suppress("ktlint")

/*
 * R4NlCoreHealthcareProviderOrganization.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class R4NlCoreHealthcareProviderOrganization(
    val organizationType: List<MgoCodeableConcept>? = null,
    val identifier: List<MgoIdentifier>? = null,
    val emailAddresses: List<R4NlCoreContactInformationEmailAddresses>? = null,
    val address: List<R4NlCoreAddressInformation>? = null,
    val profile: String = "http://nictiz.nl/fhir/StructureDefinition/nl-core-HealthcareProvider-Organization",
    val fhirVersion: String = "R4",
    val name: MgoString? = null,
    val telephoneNumbers: List<R4NlCoreContactInformationTelephoneNumbers>? = null,
    val id: String? = null,
    val departmentSpecialty: List<MgoCodeableConcept>? = null,
    val referenceId: String,
    val resourceType: String
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str1) { "fhirVersion not constant value $cg_str1 - $fhirVersion" }
    }

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/nl-core-HealthcareProvider-Organization"
        private const val cg_str1 = "R4"
    }

}
