@file:Suppress("ktlint")

/*
 * R4NlCoreAddressInformation.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class R4NlCoreAddressInformation(
    val line: String? = null,
    val streetName: String? = null,
    val houseNumber: String? = null,
    val houseNumberAddition: String? = null,
    val houseNumberIndication: String? = null,
    val additionalInformation: String? = null,
    val city: String? = null,
    val district: String? = null,
    val postalCode: String? = null,
    val country: String? = null,
    val countryCode: MgoCodeableConcept? = null,
    val addressType: MgoCodeableConcept? = null,
    val period: MgoPeriod? = null
)
