@file:Suppress("ktlint")

/*
 * R4NlCorePatient.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class R4NlCorePatient(
    val identifier: Identifier,
    val address: List<Addres>? = null,
    val gender: Gender,
    val multipleBirthBoolean: MgoBoolean? = null,
    val profile: String = "http://nictiz.nl/fhir/StructureDefinition/nl-core-Patient",
    val birthDate: MgoDate? = null,
    val referenceId: String,
    val deceasedBoolean: MgoBoolean? = null,
    val nationality: List<ExtensionValue_Of_structure_0_04577354127746314>,
    val multipleBirthInteger: MgoInteger? = null,
    val contact: List<Contact>? = null,
    val deceasedDateTime: MgoDateTime? = null,
    val fhirVersion: String = "R4",
    val name: List<R4NlCorePatientName>? = null,
    val telecom: R4NlCoreContactInformation,
    val id: String? = null,
    val communication: List<Communication>? = null,
    val maritalStatus: MgoCodeableConcept? = null,
    val resourceType: String
) {

    init {
        require(profile == cg_str1) { "profile not constant value $cg_str1 - $profile" }
        require(fhirVersion == cg_str3) { "fhirVersion not constant value $cg_str3 - $fhirVersion" }
    }

    @Serializable
    data class Identifier(
        val bsn: MgoIdentifier? = null
    )

    @Serializable
    data class Addres(
        val country: Country,
        val _profile: String,
        val city: MgoString? = null,
        val use: MgoCode_Of_string? = null,
        val line: List<Line>? = null,
        val district: MgoString? = null,
        val postalCode: MgoString? = null,
        val type: MgoCode_Of_string? = null
    ) {

        init {
            require(_profile == cg_str0) { "_profile not constant value $cg_str0 - $_profile" }
        }

    }

    @Serializable
    data class Country(
        val countryCode: MgoCodeableConcept? = null
    )

    @Serializable
    data class Line(
        val additionalInformation: MgoString? = null,
        val streetName: MgoString? = null,
        val houseNumberLetter: MgoString? = null,
        val countryCode: MgoString? = null,
        val houseNumber: MgoString? = null,
        val houseNumberAddition: MgoString? = null,
        val houseNumberIndiciation: MgoString? = null
    )

    @Serializable
    data class Gender(
        val genderCodelist: ExtensionValue_Of_MgoCodeableConcept? = null
    )

    @Serializable
    data class Contact(
        val address: R4NlCoreAddressInformation,
        val _profile: String,
        val name: List<R4NlCorePatientPropertiesContactItemsPropertiesName>,
        val telecom: R4NlCoreContactInformation,
        val relationship: Relationship
    ) {

        init {
            require(_profile == cg_str2) { "_profile not constant value $cg_str2 - $_profile" }
        }

    }

    @Serializable
    data class Relationship(
        val role: List<MgoCodeableConcept>? = null,
        val relationship: List<MgoCodeableConcept>? = null
    )

    @Serializable
    data class Communication(
        val languageProficiency: LanguageProficiency,
        val comment: List<ExtensionValue_Of_MgoString>,
        val language: MgoCodeableConcept? = null
    )

    @Serializable
    data class LanguageProficiency(
        val languageControlReading: MgoCoding? = null,
        val languageControlListening: MgoCoding? = null,
        val languageControlSpeaking: MgoCoding? = null
    )

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/nl-core-AddressInformation"
        private const val cg_str1 = "http://nictiz.nl/fhir/StructureDefinition/nl-core-Patient"
        private const val cg_str2 = "http://nictiz.nl/fhir/StructureDefinition/nl-core-ContactPerson"
        private const val cg_str3 = "R4"
    }

}
