@file:Suppress("ktlint")

/*
 * R4NlCorePharmaceuticalProduct.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class R4NlCorePharmaceuticalProduct(
    val identifier: List<MgoIdentifier>? = null,
    val amount: MgoRatio? = null,
    val code: MgoCodeableConcept? = null,
    val ingredient: List<Ingredient>? = null,
    val profile: String = "http://nictiz.nl/fhir/StructureDefinition/nl-core-PharmaceuticalProduct",
    val batch: Batch,
    val description: MgoString? = null,
    val referenceId: String,
    val manufacturer: MgoReference? = null,
    val form: MgoCodeableConcept? = null,
    val fhirVersion: String = "R4",
    val name: MgoString? = null,
    val id: String? = null,
    val status: R4NlCorePharmaceuticalProductStatus? = null,
    val resourceType: String
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str1) { "fhirVersion not constant value $cg_str1 - $fhirVersion" }
    }

    @Serializable
    data class Ingredient(
        val itemReference: MgoReference? = null,
        val strength: MgoRatio? = null,
        val itemCodeableConcept: MgoCodeableConcept? = null
    )

    @Serializable
    data class Batch(
        val lotNumber: MgoString? = null,
        val expirationDate: MgoDateTime? = null
    )

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/nl-core-PharmaceuticalProduct"
        private const val cg_str1 = "R4"
    }

}
