@file:Suppress("ktlint")

/*
 * R4NlCorePatient.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class R4NlCorePatient(
    val identifier: List<MgoIdentifier>? = null,
    val birthDate: String? = null,
    val gender: Gender? = null,
    val multipleBirth: Boolean? = null,
    val deceased: Boolean? = null,
    val deceasedDateTime: String? = null,
    val address: List<R4NlCoreAddressInformation>? = null,
    val generalPractitioner: List<MgoReference>? = null,
    val managingOrganization: MgoReference? = null,
    val maritalStatus: MgoCodeableConcept? = null,
    val id: String? = null,
    val referenceId: String,
    val resourceType: String? = null,
    val profile: String,
    val fhirVersion: String
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str1) { "fhirVersion not constant value $cg_str1 - $fhirVersion" }
    }

    @Serializable
    enum class Gender {
        unknown,
        male,
        female,
        other
    }

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/nl-core-Patient"
        private const val cg_str1 = "R4"
    }

}
