@file:Suppress("ktlint")

/*
 * R4NlCoreAddressInformation.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class R4NlCoreAddressInformation(
    val additionalInformation: MgoString? = null,
    val country: MgoString? = null,
    val period: MgoPeriod? = null,
    val city: MgoString? = null,
    val line: MgoString? = null,
    val addressType: MgoCodeableConcept? = null,
    val postalCode: MgoString? = null,
    val houseNumber: MgoString? = null,
    val houseNumberAddition: MgoString? = null,
    val streetName: MgoString? = null,
    val houseNumberIndication: MgoString? = null,
    val countryCode: MgoCodeableConcept? = null,
    val district: MgoString? = null
)
