@file:Suppress("ktlint")

/*
 * ZibAdministrationAgreement.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class ZibAdministrationAgreement(
    val additionalInformation: MgoCodeableConcept? = null,
    val identifier: List<MgoIdentifier>? = null,
    val note: List<MgoAnnotation>? = null,
    val agreementReason: String? = null,
    val medicationTreatment: MgoIdentifier? = null,
    val authoredOn: String? = null,
    val quantity: MgoQuantity? = null,
    val performer: List<Performer>? = null,
    val daysSupply: MgoQuantity? = null,
    val profile: String,
    val stopType: MgoCodeableConcept? = null,
    val dossageInstruction: List<ZibInstructionsForUse>? = null,
    val referenceId: String,
    val repeatPeriodCyclicalSchedule: MgoQuantity? = null,
    val medicationReference: MgoReference? = null,
    val periodOfUse: MgoPeriod? = null,
    val usageDuration: MgoQuantity? = null,
    val fhirVersion: String,
    val id: String? = null,
    val category: MgoCodeableConcept? = null,
    val authorizingPrescription: List<MgoReference>? = null,
    val status: String? = null,
    val resourceType: String? = null
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str1) { "fhirVersion not constant value $cg_str1 - $fhirVersion" }
        if (status != null)
            require(status in cg_array2) { "status not in enumerated values - $status" }
    }

    @Serializable
    data class Performer(
        val actor: MgoReference? = null,
        val onBehalfOf: MgoReference? = null
    )

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/zib-AdministrationAgreement"
        private const val cg_str1 = "R3"
        private val cg_array2 = setOf(
            "entered-in-error",
            "preparation",
            "in-progress",
            "on-hold",
            "completed",
            "stopped"
        )
    }

}
