@file:Suppress("ktlint")

/*
 * ZibAllergyIntolerance.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class ZibAllergyIntolerance(
    val identifier: List<MgoIdentifier>? = null,
    val code: MgoCodeableConcept? = null,
    val verificationStatus: String? = null,
    val profile: String,
    val criticality: String? = null,
    val clinicalStatus: ClinicalStatus? = null,
    val type: Type? = null,
    val referenceId: String,
    val patient: MgoReference? = null,
    val fhirVersion: String,
    val id: String? = null,
    val category: List<String>? = null,
    val resourceType: String? = null
) {

    init {
        if (verificationStatus != null)
            require(verificationStatus in cg_array0) { "verificationStatus not in enumerated values - $verificationStatus" }
        require(profile == cg_str1) { "profile not constant value $cg_str1 - $profile" }
        if (criticality != null)
            require(criticality in cg_array2) { "criticality not in enumerated values - $criticality" }
        require(fhirVersion == cg_str3) { "fhirVersion not constant value $cg_str3 - $fhirVersion" }
    }

    @Serializable
    enum class ClinicalStatus {
        active,
        inactive,
        resolved
    }

    @Serializable
    enum class Type {
        allergy,
        intolerance
    }

    companion object {
        private val cg_array0 = setOf(
            "entered-in-error",
            "unconfirmed",
            "confirmed",
            "refuted"
        )
        private const val cg_str1 = "http://nictiz.nl/fhir/StructureDefinition/zib-AllergyIntolerance"
        private val cg_array2 = setOf(
            "high",
            "low",
            "unable-to-assess"
        )
        private const val cg_str3 = "R3"
    }

}
