@file:Suppress("ktlint")

/*
 * ZibAdvanceDirective.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class ZibAdvanceDirective(
    val sourceReference: MgoReference? = null,
    val dateTime: MgoDateTime? = null,
    val identifier: MgoIdentifier? = null,
    val sourceIdentifier: MgoIdentifier? = null,
    val profile: String = "http://nictiz.nl/fhir/StructureDefinition/zib-AdvanceDirective",
    val sourceAttachment: MgoAttachment? = null,
    val referenceId: String,
    val disorder: List<Disorder>,
    val consentingParty: MgoReference? = null,
    val fhirVersion: String = "R3",
    val comment: Comment? = null,
    val id: String? = null,
    val category: Category,
    val resourceType: String
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str2) { "fhirVersion not constant value $cg_str2 - $fhirVersion" }
    }

    @Serializable
    data class Disorder(
        val reference: String? = null,
        val display: String? = null,
        val _type: String,
        val _ext: Boolean
    ) {

        init {
            require(_type == cg_str1) { "_type not constant value $cg_str1 - $_type" }
        }

    }

    @Serializable
    data class Comment(
        val _type: String,
        val value: String,
        val _ext: Boolean
    ) {

        init {
            require(_type == cg_str3) { "_type not constant value $cg_str3 - $_type" }
        }

    }

    @Serializable
    data class Category(
        val typeOfLivingWill: List<MgoCodeableConcept>? = null
    )

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/zib-AdvanceDirective"
        private const val cg_str1 = "reference"
        private const val cg_str2 = "R3"
        private const val cg_str3 = "string"
    }

}
