@file:Suppress("ktlint")

/*
 * ZibAllergyIntolerance.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class ZibAllergyIntolerance(
    val identifier: List<MgoIdentifier>? = null,
    val code: MgoCodeableConcept? = null,
    val verificationStatus: ZibAllergyIntoleranceVerificationstatus? = null,
    val profile: String = "http://nictiz.nl/fhir/StructureDefinition/zib-AllergyIntolerance",
    val criticality: ZibAllergyIntoleranceCriticality? = null,
    val clinicalStatus: ZibAllergyIntoleranceClinicalstatus? = null,
    val type: ZibAllergyIntoleranceType? = null,
    val referenceId: String,
    val patient: MgoReference? = null,
    val fhirVersion: String = "R3",
    val id: String? = null,
    val category: List<ZibAllergyIntoleranceCategory>? = null,
    val resourceType: String
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str1) { "fhirVersion not constant value $cg_str1 - $fhirVersion" }
    }

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/zib-AllergyIntolerance"
        private const val cg_str1 = "R3"
    }

}
