@file:Suppress("ktlint")

/*
 * ZibAlcoholUse.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class ZibAlcoholUse(
    val id: String? = null,
    val referenceId: String,
    val resourceType: String? = null,
    val profile: String,
    val fhirVersion: String,
    val identifier: List<MgoIdentifier>? = null,
    val status: String? = null,
    val category: List<MgoCodeableConcept>? = null,
    val subject: MgoReference? = null,
    val context: MgoReference? = null,
    val valueQuantity: MgoQuantity? = null,
    val effectivePeriod: MgoPeriod? = null,
    val dataAbsentReason: MgoCodeableConcept? = null,
    val method: MgoCodeableConcept? = null,
    val bodySite: MgoCodeableConcept? = null,
    val comment: String? = null
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str1) { "fhirVersion not constant value $cg_str1 - $fhirVersion" }
        if (status != null)
            require(status in cg_array2) { "status not in enumerated values - $status" }
    }

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/zib-AlcoholUse"
        private const val cg_str1 = "R3"
        private val cg_array2 = setOf(
            "registered",
            "preliminary",
            "final",
            "amended",
            "corrected",
            "cancelled",
            "entered-in-error",
            "unknown"
        )
    }

}
