@file:Suppress("ktlint")

/*
 * ZibAlert.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class ZibAlert(
    val identifier: List<MgoIdentifier>? = null,
    val period: MgoPeriod? = null,
    val code: MgoCodeableConcept? = null,
    val author: MgoReference? = null,
    val patient: MgoReference? = null,
    val concernReference: ConcernReference? = null,
    val profile: String = "http://nictiz.nl/fhir/StructureDefinition/zib-Alert",
    val fhirVersion: String = "R3",
    val id: String? = null,
    val category: MgoCodeableConcept? = null,
    val referenceId: String,
    val resourceType: String
) {

    init {
        require(profile == cg_str1) { "profile not constant value $cg_str1 - $profile" }
        require(fhirVersion == cg_str2) { "fhirVersion not constant value $cg_str2 - $fhirVersion" }
    }

    @Serializable
    data class ConcernReference(
        val reference: String? = null,
        val display: String? = null,
        val _type: String,
        val _ext: Boolean
    ) {

        init {
            require(_type == cg_str0) { "_type not constant value $cg_str0 - $_type" }
        }

    }

    companion object {
        private const val cg_str0 = "reference"
        private const val cg_str1 = "http://nictiz.nl/fhir/StructureDefinition/zib-Alert"
        private const val cg_str2 = "R3"
    }

}
