@file:Suppress("ktlint")

/*
 * ZibAdvanceDirective.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class ZibAdvanceDirective(
    val category: List<MgoCodeableConcept>? = null,
    val dateTime: String? = null,
    val disorder: MgoReference? = null,
    val consentingParty: List<MgoReference>? = null,
    val source: Source,
    val comment: String? = null,
    val id: String? = null,
    val referenceId: String,
    val resourceType: String? = null,
    val profile: String,
    val fhirVersion: String
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str1) { "fhirVersion not constant value $cg_str1 - $fhirVersion" }
    }

    @Serializable
    data class Source(
        val attachment: Attachment,
        val identifier: MgoIdentifier? = null,
        val reference: MgoReference? = null
    )

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/zib-AdvanceDirective"
        private const val cg_str1 = "R3"
    }

}
