@file:Suppress("ktlint")

/*
 * ZibAdministrationSchedule.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlin.Double

import kotlinx.serialization.Serializable

@Serializable
data class ZibAdministrationSchedule(
    val repeat: Repeat
) {

    @Serializable
    data class Repeat(
        val boundsDuration: MgoDuration? = null,
        val boundsPeriod: MgoPeriod? = null,
        val boundsRange: MgoRange? = null,
        val duration: Double? = null,
        val durationUnit: String? = null,
        val frequency: Double? = null,
        val frequencyMax: Double? = null,
        val period: Double? = null,
        val periodUnit: String? = null,
        val dayOfWeek: List<String>? = null,
        val timeOfDay: List<String>? = null,
        val `when`: List<String>? = null
    )

}
