@file:Suppress("ktlint")

/*
 * ZibAdministrationAgreement.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class ZibAdministrationAgreement(
    val authoredOn: String? = null,
    val agreementReason: String? = null,
    val usageDuration: MgoQuantity? = null,
    val additionalInformation: MgoCodeableConcept? = null,
    val medicationTreatment: MgoIdentifier? = null,
    val stopType: MgoCodeableConcept? = null,
    val repeatPeriodCyclicalSchedule: MgoQuantity? = null,
    val identifier: List<MgoIdentifier>? = null,
    val status: String? = null,
    val category: MgoCodeableConcept? = null,
    val medicationReference: MgoReference? = null,
    val quantity: MgoQuantity? = null,
    val daysSupply: MgoQuantity? = null,
    val note: List<MgoAnnotation>? = null,
    val dossageInstruction: List<ZibInstructionsForUse>? = null,
    val id: String? = null,
    val referenceId: String,
    val resourceType: String? = null,
    val profile: String,
    val fhirVersion: String
) {

    init {
        if (status != null)
            require(status in cg_array0) { "status not in enumerated values - $status" }
        require(profile == cg_str1) { "profile not constant value $cg_str1 - $profile" }
        require(fhirVersion == cg_str2) { "fhirVersion not constant value $cg_str2 - $fhirVersion" }
    }

    companion object {
        private val cg_array0 = setOf(
            "entered-in-error",
            "preparation",
            "in-progress",
            "on-hold",
            "completed",
            "stopped"
        )
        private const val cg_str1 = "http://nictiz.nl/fhir/StructureDefinition/zib-AdministrationAgreement"
        private const val cg_str2 = "R3"
    }

}
