@file:Suppress("ktlint")

/*
 * ZibAlert.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class ZibAlert(
    val identifier: List<MgoIdentifier>? = null,
    val period: MgoPeriod? = null,
    val code: MgoCodeableConcept? = null,
    val subject: MgoReference? = null,
    val author: MgoReference? = null,
    val profile: String,
    val encounter: MgoReference? = null,
    val referenceId: String,
    val fhirVersion: String,
    val id: String? = null,
    val category: MgoCodeableConcept? = null,
    val status: String? = null,
    val resourceType: String? = null
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str1) { "fhirVersion not constant value $cg_str1 - $fhirVersion" }
        if (status != null)
            require(status in cg_array2) { "status not in enumerated values - $status" }
    }

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/zib-Alert"
        private const val cg_str1 = "R3"
        private val cg_array2 = setOf(
            "active",
            "entered-in-error",
            "inactive"
        )
    }

}
