@file:Suppress("ktlint")

/*
 * ZibBloodPressure.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class ZibBloodPressure(
    val dataAbsentReason: MgoCodeableConcept? = null,
    val averageBloodPressureLOINC: AverageBloodPressureLOINC,
    val diastolicEndpoint: DiastolicEndpoint,
    val subject: MgoReference? = null,
    val cuffTypeLOINC: CuffTypeLOINC,
    val diastolicBP: DiastolicBP,
    val referenceId: String,
    val cuffTypeSNOMED: CuffTypeSNOMED,
    val valueCodeableConcept: MgoCodeableConcept? = null,
    val systolicBP: SystolicBP,
    val fhirVersion: String = "R3",
    val context: MgoReference? = null,
    val id: String? = null,
    val valueQuantity: MgoQuantity? = null,
    val identifier: List<MgoIdentifier>? = null,
    val effectivePeriod: MgoPeriod? = null,
    val method: MgoCodeableConcept? = null,
    val profile: String = "http://nictiz.nl/fhir/StructureDefinition/zib-BloodPressure",
    val positionSNOMED: PositionSNOMED,
    val bodySite: MgoCodeableConcept? = null,
    val effectiveDateTime: String? = null,
    val comment: String? = null,
    val averageBloodPressureSNOMED: AverageBloodPressureSNOMED,
    val category: List<MgoCodeableConcept>? = null,
    val positionLOINC: PositionLOINC,
    val resourceType: String? = null,
    val status: String? = null
) {

    init {
        require(fhirVersion == cg_str0) { "fhirVersion not constant value $cg_str0 - $fhirVersion" }
        require(profile == cg_str1) { "profile not constant value $cg_str1 - $profile" }
        if (status != null)
            require(status in cg_array2) { "status not in enumerated values - $status" }
    }

    @Serializable
    data class AverageBloodPressureLOINC(
        val valueQuantity: MgoQuantity? = null
    )

    @Serializable
    data class DiastolicEndpoint(
        val valueCodeableConcept: MgoCodeableConcept? = null
    )

    @Serializable
    data class CuffTypeLOINC(
        val valueCodeableConcept: MgoCodeableConcept? = null
    )

    @Serializable
    data class DiastolicBP(
        val valueQuantity: MgoQuantity? = null
    )

    @Serializable
    data class CuffTypeSNOMED(
        val valueCodeableConcept: MgoCodeableConcept? = null
    )

    @Serializable
    data class SystolicBP(
        val valueQuantity: MgoQuantity? = null
    )

    @Serializable
    data class PositionSNOMED(
        val valueCodeableConcept: MgoCodeableConcept? = null
    )

    @Serializable
    data class AverageBloodPressureSNOMED(
        val valueQuantity: MgoQuantity? = null
    )

    @Serializable
    data class PositionLOINC(
        val valueCodeableConcept: MgoCodeableConcept? = null
    )

    companion object {
        private const val cg_str0 = "R3"
        private const val cg_str1 = "http://nictiz.nl/fhir/StructureDefinition/zib-BloodPressure"
        private val cg_array2 = setOf(
            "registered",
            "preliminary",
            "final",
            "amended",
            "corrected",
            "cancelled",
            "entered-in-error",
            "unknown"
        )
    }

}
