@file:Suppress("ktlint")

/*
 * ZibEncounter.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class ZibEncounter(
    val identifier: List<MgoIdentifier>? = null,
    val reason: List<MgoCodeableConcept>? = null,
    val period: MgoPeriod? = null,
    val hospitalization: Hospitalization,
    val subject: MgoReference? = null,
    val profile: String = "http://nictiz.nl/fhir/StructureDefinition/zib-Encounter",
    val diagnosis: List<Diagnosi>? = null,
    val participant: List<Participant>? = null,
    val referenceId: String,
    val fhirVersion: String = "R3",
    val serviceProvider: MgoReference? = null,
    val id: String? = null,
    val `class`: MgoCoding? = null,
    val resourceType: String
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str1) { "fhirVersion not constant value $cg_str1 - $fhirVersion" }
    }

    @Serializable
    data class Hospitalization(
        val dischargeDisposition: MgoCodeableConcept? = null,
        val admitSource: MgoCodeableConcept? = null
    )

    @Serializable
    data class Diagnosi(
        val condition: MgoReference? = null
    )

    @Serializable
    data class Participant(
        val individual: MgoReference? = null,
        val type: Type
    )

    @Serializable
    data class Type(
        val healthProfessionalRole: List<MgoCodeableConcept>? = null
    )

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/zib-Encounter"
        private const val cg_str1 = "R3"
    }

}
