@file:Suppress("ktlint")

/*
 * ZibInstructionsForUse.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlin.Double

import kotlinx.serialization.Serializable

@Serializable
data class ZibInstructionsForUse(
    val asNeeded: MgoCodeableConcept? = null,
    val sequence: Double? = null,
    val additionalInstruction: List<MgoCodeableConcept>? = null,
    val rateRatio: MgoRatio? = null,
    val route: MgoCodeableConcept? = null,
    val rateRange: MgoRange? = null,
    val doseRange: MgoRange? = null,
    val doseQuantity: MgoQuantity? = null,
    val timing: ZibAdministrationSchedule,
    val rateQuantity: MgoQuantity? = null,
    val maxDosePerPeriod: MgoRatio? = null,
    val text: String? = null
)
