@file:Suppress("ktlint")

/*
 * ZibInstructionsForUse.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class ZibInstructionsForUse(
    val additionalInstruction: List<MgoCodeableConcept>? = null,
    val rateRatio: MgoRatio? = null,
    val doseQuantity: MgoQuantityProps? = null,
    val timing: ZibAdministrationSchedule,
    val rateQuantity: MgoQuantityProps? = null,
    val sequence: MgoInteger? = null,
    val route: MgoCodeableConcept? = null,
    val rateRange: MgoRange? = null,
    val _profile: String = "http://nictiz.nl/fhir/StructureDefinition/zib-InstructionsForUse",
    val doseRange: MgoRange? = null,
    val maxDosePerPeriod: MgoRatio? = null,
    val text: MgoString? = null,
    val asNeededCodeableConcept: MgoCodeableConcept? = null
) {

    init {
        require(_profile == cg_str0) { "_profile not constant value $cg_str0 - $_profile" }
    }

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/zib-InstructionsForUse"
    }

}
