@file:Suppress("ktlint")

/*
 * ZibLaboratoryTestResultSpecimenIsolate.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class ZibLaboratoryTestResultSpecimenIsolate(
    val container: List<Container>? = null,
    val identifier: List<MgoIdentifier>? = null,
    val parent: List<MgoReference>? = null,
    val note: List<MgoAnnotation>? = null,
    val subject: MgoReference? = null,
    val profile: String = "http://nictiz.nl/fhir/StructureDefinition/zib-LaboratoryTestResult-Specimen-Isolate",
    val collection: Collection,
    val type: MgoCodeableConcept? = null,
    val referenceId: String,
    val receivedTime: MgoDateTime? = null,
    val fhirVersion: String = "R3",
    val id: String? = null,
    val resourceType: String
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str1) { "fhirVersion not constant value $cg_str1 - $fhirVersion" }
    }

    @Serializable
    data class Container(
        val identifier: List<MgoIdentifier>? = null,
        val type: MgoCodeableConcept? = null
    )

    @Serializable
    data class Collection(
        val bodySite: BodySite,
        val quantity: MgoQuantity? = null,
        val method: MgoCodeableConcept? = null,
        val collectedPeriod: MgoPeriod? = null,
        val collectedDateTime: MgoDateTime? = null
    )

    @Serializable
    data class BodySite(
        val morphology: ExtensionValue_Of_MgoCodeableConcept? = null,
        val value: MgoCodeableConcept? = null,
        val laterality: ExtensionValue_Of_MgoCodeableConcept? = null
    )

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/zib-LaboratoryTestResult-Specimen-Isolate"
        private const val cg_str1 = "R3"
    }

}
