@file:Suppress("ktlint")

/*
 * ZibMedicationUse.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class ZibMedicationUse(
    val prescriber: ExtensionValue_Of_MgoReference? = null,
    val identifier: List<MgoIdentifier>? = null,
    val note: List<MgoAnnotation>? = null,
    val dosage: List<Dosage>? = null,
    val medicationTreatment: ExtensionValue_Of_MgoIdentifier? = null,
    val effectivePeriod: EffectivePeriod,
    val author: ExtensionValue_Of_MgoReference? = null,
    val subject: MgoReference? = null,
    val profile: String = "http://nictiz.nl/fhir/StructureDefinition/zib-MedicationUse",
    val referenceId: String,
    val medicationReference: MgoReference? = null,
    val repeatPeriodCyclicalSchedule: ExtensionValue_Of_MgoDuration? = null,
    val asAgreedIndicator: ExtensionValue_Of_MgoBoolean? = null,
    val informationSource: MgoReference? = null,
    val taken: MgoCode_Of_y_n_unk_na? = null,
    val fhirVersion: String = "R3",
    val reasonCode: List<MgoCodeableConcept>? = null,
    val id: String? = null,
    val dateAsserted: MgoDateTime? = null,
    val reasonForChangeOrDiscontinuationOfUse: ExtensionValue_Of_MgoCodeableConcept? = null,
    val status: MgoCode_Of_entered_in_error_on_hold_completed_stopped_active_intended? = null,
    val resourceType: String
) {

    init {
        require(profile == cg_str2) { "profile not constant value $cg_str2 - $profile" }
        require(fhirVersion == cg_str3) { "fhirVersion not constant value $cg_str3 - $fhirVersion" }
    }

    @Serializable
    data class Dosage(
        val additionalInstruction: List<MgoCodeableConcept>? = null,
        val rateRatio: MgoRatio? = null,
        val doseQuantity: MgoQuantityProps? = null,
        val timing: ZibAdministrationSchedule,
        val rateQuantity: MgoQuantityProps? = null,
        val sequence: MgoInteger? = null,
        val route: MgoCodeableConcept? = null,
        val rateRange: MgoRange? = null,
        val _profile: String,
        val doseRange: MgoRange? = null,
        val maxDosePerPeriod: MgoRatio? = null,
        val text: MgoString? = null,
        val asNeededCodeableConcept: MgoCodeableConcept? = null
    ) {

        init {
            require(_profile == cg_str0) { "_profile not constant value $cg_str0 - $_profile" }
        }

    }

    @Serializable
    data class EffectivePeriod(
        val duration: ExtensionValue_Of_MgoDuration? = null,
        val start: String? = null,
        val _type: String,
        val end: String? = null
    ) {

        init {
            require(_type == cg_str1) { "_type not constant value $cg_str1 - $_type" }
        }

    }

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/zib-InstructionsForUse"
        private const val cg_str1 = "period"
        private const val cg_str2 = "http://nictiz.nl/fhir/StructureDefinition/zib-MedicationUse"
        private const val cg_str3 = "R3"
    }

}
