@file:Suppress("ktlint")

/*
 * ZibMedicationAgreement.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlin.Double

import kotlinx.serialization.Serializable

@Serializable
data class ZibMedicationAgreement(
    val requester: MgoReference? = null,
    val identifier: List<MgoIdentifier>? = null,
    val additionalInformation: AdditionalInformation? = null,
    val note: List<MgoAnnotation>? = null,
    val medicationTreatment: MedicationTreatment? = null,
    val authoredOn: MgoDateTime? = null,
    val profile: String = "http://nictiz.nl/fhir/StructureDefinition/zib-MedicationAgreement",
    val reasonReference: List<MgoReference>? = null,
    val stopType: StopType? = null,
    val dossageInstruction: List<DossageInstruction>? = null,
    val referenceId: String,
    val medicationReference: MgoReference? = null,
    val repeatPeriodCyclicalSchedule: RepeatPeriodCyclicalSchedule? = null,
    val periodOfUse: PeriodOfUse? = null,
    val usageDuration: UsageDuration? = null,
    val patient: MgoReference? = null,
    val fhirVersion: String = "R3",
    val reasonCode: List<MgoCodeableConcept>? = null,
    val id: String? = null,
    val resourceType: String
) {

    init {
        require(profile == cg_str2) { "profile not constant value $cg_str2 - $profile" }
        require(fhirVersion == cg_str6) { "fhirVersion not constant value $cg_str6 - $fhirVersion" }
    }

    @Serializable
    data class AdditionalInformation(
        val coding: List<MgoCodingProps>,
        val _type: String,
        val text: String? = null,
        val _ext: Boolean
    ) {

        init {
            require(_type == cg_str0) { "_type not constant value $cg_str0 - $_type" }
        }

    }

    @Serializable
    data class MedicationTreatment(
        val system: String? = null,
        val use: String? = null,
        val _type: String,
        val type: Type? = null,
        val value: String? = null,
        val _ext: Boolean
    ) {

        init {
            require(_type == cg_str1) { "_type not constant value $cg_str1 - $_type" }
        }

    }

    @Serializable
    data class Type(
        val coding: List<MgoCodingProps>,
        val text: String? = null
    )

    @Serializable
    data class StopType(
        val coding: List<MgoCodingProps>,
        val _type: String,
        val text: String? = null,
        val _ext: Boolean
    ) {

        init {
            require(_type == cg_str0) { "_type not constant value $cg_str0 - $_type" }
        }

    }

    @Serializable
    data class DossageInstruction(
        val additionalInstruction: List<MgoCodeableConcept>? = null,
        val rateRatio: MgoRatio? = null,
        val doseQuantity: MgoQuantityProps? = null,
        val timing: ZibAdministrationSchedule,
        val rateQuantity: MgoQuantityProps? = null,
        val sequence: MgoInteger? = null,
        val route: MgoCodeableConcept? = null,
        val rateRange: MgoRange? = null,
        val _profile: String,
        val doseRange: MgoRange? = null,
        val maxDosePerPeriod: MgoRatio? = null,
        val text: MgoString? = null,
        val asNeededCodeableConcept: MgoCodeableConcept? = null
    ) {

        init {
            require(_profile == cg_str3) { "_profile not constant value $cg_str3 - $_profile" }
        }

    }

    @Serializable
    data class RepeatPeriodCyclicalSchedule(
        val comparator: String? = null,
        val unit: String? = null,
        val system: String? = null,
        val code: String? = null,
        val _type: String,
        val value: Double? = null,
        val _ext: Boolean
    ) {

        init {
            require(_type == cg_str4) { "_type not constant value $cg_str4 - $_type" }
        }

    }

    @Serializable
    data class PeriodOfUse(
        val _type: String,
        val start: String? = null,
        val end: String? = null,
        val _ext: Boolean
    ) {

        init {
            require(_type == cg_str5) { "_type not constant value $cg_str5 - $_type" }
        }

    }

    @Serializable
    data class UsageDuration(
        val comparator: String? = null,
        val unit: String? = null,
        val system: String? = null,
        val code: String? = null,
        val _type: String,
        val value: Double? = null,
        val _ext: Boolean
    ) {

        init {
            require(_type == cg_str4) { "_type not constant value $cg_str4 - $_type" }
        }

    }

    companion object {
        private const val cg_str0 = "codeableConcept"
        private const val cg_str1 = "identifier"
        private const val cg_str2 = "http://nictiz.nl/fhir/StructureDefinition/zib-MedicationAgreement"
        private const val cg_str3 = "http://nictiz.nl/fhir/StructureDefinition/zib-InstructionsForUse"
        private const val cg_str4 = "duration"
        private const val cg_str5 = "period"
        private const val cg_str6 = "R3"
    }

}
