@file:Suppress("ktlint")

/*
 * ZibMedicalDeviceRequest.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class ZibMedicalDeviceRequest(
    val codeReference: MgoReference? = null,
    val subject: MgoReference? = null,
    val perfomer: MgoReference? = null,
    val profile: String = "http://nictiz.nl/fhir/StructureDefinition/zib-MedicalDeviceRequest",
    val fhirVersion: String = "R3",
    val occurrence: MgoPeriod? = null,
    val id: String? = null,
    val intent: MgoCodeableConcept? = null,
    val codeCodeableConcept: MgoCodeableConcept? = null,
    val referenceId: String,
    val status: MgoString? = null,
    val resourceType: String
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str1) { "fhirVersion not constant value $cg_str1 - $fhirVersion" }
    }

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/zib-MedicalDeviceRequest"
        private const val cg_str1 = "R3"
    }

}
