@file:Suppress("ktlint")

/*
 * ZibMedicalDevice.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class ZibMedicalDevice(
    val identifier: List<MgoIdentifier>? = null,
    val organization: MgoReference? = null,
    val practitioner: MgoReference? = null,
    val reason: MgoReference? = null,
    val status: String? = null,
    val patient: MgoReference? = null,
    val whenUsed: MgoPeriod? = null,
    val recordedOn: String? = null,
    val source: MgoReference? = null,
    val device: MgoReference? = null,
    val bodySite: MgoCodeableConcept? = null,
    val laterality: MgoCodeableConcept? = null,
    val note: List<MgoAnnotation>? = null,
    val id: String? = null,
    val referenceId: String,
    val resourceType: String? = null,
    val profile: String,
    val fhirVersion: String
) {

    init {
        if (status != null)
            require(status in cg_array0) { "status not in enumerated values - $status" }
        require(profile == cg_str1) { "profile not constant value $cg_str1 - $profile" }
        require(fhirVersion == cg_str2) { "fhirVersion not constant value $cg_str2 - $fhirVersion" }
    }

    companion object {
        private val cg_array0 = setOf(
            "active",
            "entered-in-error",
            "on-hold",
            "completed",
            "stopped",
            "intended"
        )
        private const val cg_str1 = "http://nictiz.nl/fhir/StructureDefinition/zib-MedicalDevice"
        private const val cg_str2 = "R3"
    }

}
