@file:Suppress("ktlint")

/*
 * ZibMedicationUse.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class ZibMedicationUse(
    val prescriber: MgoReference? = null,
    val identifier: List<MgoIdentifier>? = null,
    val note: List<MgoAnnotation>? = null,
    val dosage: List<ZibInstructionsForUse>? = null,
    val medicationTreatment: MgoIdentifier? = null,
    val effectivePeriod: MgoPeriod? = null,
    val author: MgoReference? = null,
    val subject: MgoReference? = null,
    val profile: String = "http://nictiz.nl/fhir/StructureDefinition/zib-MedicationUse",
    val referenceId: String,
    val repeatPeriodCyclicalSchedule: MgoQuantity? = null,
    val medicationReference: MgoReference? = null,
    val asAgreedIndicator: Boolean? = null,
    val informationSource: MgoReference? = null,
    val taken: Taken? = null,
    val fhirVersion: String = "R3",
    val effectiveDuration: MgoQuantity? = null,
    val reasonCode: List<MgoCodeableConcept>? = null,
    val id: String? = null,
    val category: MgoCodeableConcept? = null,
    val dateAsserted: String? = null,
    val reasonForChangeOrDiscontinuationOfUse: MgoCodeableConcept? = null,
    val status: String? = null,
    val resourceType: String? = null
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str1) { "fhirVersion not constant value $cg_str1 - $fhirVersion" }
        if (status != null)
            require(status in cg_array2) { "status not in enumerated values - $status" }
    }

    @Serializable
    enum class Taken {
        y,
        n,
        unk,
        na
    }

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/zib-MedicationUse"
        private const val cg_str1 = "R3"
        private val cg_array2 = setOf(
            "active",
            "entered-in-error",
            "on-hold",
            "completed",
            "stopped",
            "intended"
        )
    }

}
