@file:Suppress("ktlint")

/*
 * ZibMedicationAgreement.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class ZibMedicationAgreement(
    val identifier: List<MgoIdentifier>? = null,
    val note: List<MgoAnnotation>? = null,
    val medicationTreatment: MgoIdentifier? = null,
    val profile: String = "http://nictiz.nl/fhir/StructureDefinition/zib-MedicationAgreement",
    val stopType: MgoCodeableConcept? = null,
    val priority: Priority? = null,
    val intent: String? = null,
    val dossageInstruction: List<ZibInstructionsForUse>? = null,
    val referenceId: String,
    val repeatPeriodCyclicalSchedule: MgoQuantity? = null,
    val medicationReference: MgoReference? = null,
    val periodOfUse: MgoPeriod? = null,
    val usageDuration: MgoQuantity? = null,
    val fhirVersion: String = "R3",
    val definition: List<MgoReference>? = null,
    val id: String? = null,
    val groupIdentifier: MgoIdentifier? = null,
    val category: MgoCodeableConcept? = null,
    val basedOn: List<MgoReference>? = null,
    val status: String? = null,
    val resourceType: String? = null
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        if (intent != null)
            require(intent in cg_array1) { "intent not in enumerated values - $intent" }
        require(fhirVersion == cg_str2) { "fhirVersion not constant value $cg_str2 - $fhirVersion" }
        if (status != null)
            require(status in cg_array3) { "status not in enumerated values - $status" }
    }

    @Serializable
    enum class Priority {
        routine,
        urgent,
        stat,
        asap
    }

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/zib-MedicationAgreement"
        private val cg_array1 = setOf(
            "order",
            "plan",
            "proposal",
            "instance-order"
        )
        private const val cg_str2 = "R3"
        private val cg_array3 = setOf(
            "active",
            "cancelled",
            "entered-in-error",
            "unknown",
            "on-hold",
            "completed",
            "stopped",
            "draft"
        )
    }

}
