@file:Suppress("ktlint")

/*
 * ZibMedicalDevice.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class ZibMedicalDevice(
    val identifier: List<MgoIdentifier>? = null,
    val reason: MgoReference? = null,
    val note: List<MgoAnnotation>? = null,
    val practitioner: MgoReference? = null,
    val profile: String = "http://nictiz.nl/fhir/StructureDefinition/zib-MedicalDevice",
    val source: MgoReference? = null,
    val laterality: MgoCodeableConcept? = null,
    val referenceId: String,
    val bodySite: MgoCodeableConcept? = null,
    val whenUsed: MgoPeriod? = null,
    val patient: MgoReference? = null,
    val organization: MgoReference? = null,
    val fhirVersion: String = "R3",
    val recordedOn: MgoDateTime? = null,
    val id: String? = null,
    val device: MgoReference? = null,
    val status: ZibMedicalDeviceStatus? = null,
    val resourceType: String
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str1) { "fhirVersion not constant value $cg_str1 - $fhirVersion" }
    }

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/zib-MedicalDevice"
        private const val cg_str1 = "R3"
    }

}
