@file:Suppress("ktlint")

/*
 * ZibMedicalDeviceProduct.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class ZibMedicalDeviceProduct(
    val identifier: List<MgoIdentifier>? = null,
    val note: List<MgoAnnotation>? = null,
    val patient: MgoReference? = null,
    val profile: String = "http://nictiz.nl/fhir/StructureDefinition/zib-MedicalDeviceProduct",
    val fhirVersion: String = "R3",
    val udi: Udi,
    val lotNumber: MgoString? = null,
    val id: String? = null,
    val type: MgoCodeableConcept? = null,
    val referenceId: String,
    val expirationDate: MgoDateTime? = null,
    val resourceType: String
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str1) { "fhirVersion not constant value $cg_str1 - $fhirVersion" }
    }

    @Serializable
    data class Udi(
        val deviceIdentifier: MgoString? = null,
        val carrierHRF: MgoString? = null
    )

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/zib-MedicalDeviceProduct"
        private const val cg_str1 = "R3"
    }

}
