@file:Suppress("ktlint")

/*
 * ZibMedicalDevice.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class ZibMedicalDevice(
    val identifier: List<MgoIdentifier>? = null,
    val note: List<MgoAnnotation>? = null,
    val subject: MgoReference? = null,
    val profile: String = "http://nictiz.nl/fhir/StructureDefinition/zib-MedicalDevice",
    val source: MgoReference? = null,
    val healthCareProvider: ExtensionValue_Of_MgoReference? = null,
    val referenceId: String,
    val healthProfessional: ExtensionValue_Of_MgoReference? = null,
    val bodySite: BodySite,
    val whenUsed: MgoPeriod? = null,
    val indicationProblem: List<IndicationProblem>? = null,
    val fhirVersion: String = "R3",
    val id: String? = null,
    val device: MgoReference? = null,
    val resourceType: String
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str2) { "fhirVersion not constant value $cg_str2 - $fhirVersion" }
    }

    @Serializable
    data class BodySite(
        val coding: List<MgoCoding>? = null,
        val text: MgoString? = null,
        val laterality: ExtensionValue_Of_MgoCodeableConcept? = null
    )

    @Serializable
    data class IndicationProblem(
        val reference: String? = null,
        val display: String? = null,
        val _type: String,
        val _ext: Boolean
    ) {

        init {
            require(_type == cg_str1) { "_type not constant value $cg_str1 - $_type" }
        }

    }

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/zib-MedicalDevice"
        private const val cg_str1 = "reference"
        private const val cg_str2 = "R3"
    }

}
