@file:Suppress("ktlint")

/*
 * ZibProduct.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class ZibProduct(
    val description: String? = null,
    val code: MgoCodeableConcept? = null,
    val form: MgoCodeableConcept? = null,
    val ingredient: List<ZibProductIngredient>? = null,
    val `package`: Package,
    val id: String? = null,
    val referenceId: String,
    val resourceType: String? = null,
    val profile: String,
    val fhirVersion: String
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str1) { "fhirVersion not constant value $cg_str1 - $fhirVersion" }
    }

    @Serializable
    data class Package(
        val content: List<Content>? = null
    )

    @Serializable
    data class Content(
        val item: MgoCodeableConcept? = null,
        val reference: MgoReference? = null
    )

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/zib-Product"
        private const val cg_str1 = "R3"
    }

}
