@file:Suppress("ktlint")

/*
 * ZibProcedure.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class ZibProcedure(
    val performedPeriod: MgoPeriod? = null,
    val bodySite: List<MgoCodeableConcept>? = null,
    val bodySiteQualifier: List<MgoCodeableConcept>? = null,
    val reasonReference: List<MgoReference>? = null,
    val code: MgoCodeableConcept? = null,
    val procedureMethod: MgoCodeableConcept? = null,
    val focalDevice: List<FocalDevice>? = null,
    val location: MgoReference? = null,
    val performer: List<Performer>? = null,
    val subject: MgoReference? = null,
    val id: String? = null,
    val referenceId: String,
    val resourceType: String? = null,
    val profile: String,
    val fhirVersion: String
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str1) { "fhirVersion not constant value $cg_str1 - $fhirVersion" }
    }

    @Serializable
    data class FocalDevice(
        val manipulated: MgoReference? = null
    )

    @Serializable
    data class Performer(
        val actor: MgoReference? = null
    )

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/zib-Procedure"
        private const val cg_str1 = "R3"
    }

}
