@file:Suppress("ktlint")

/*
 * ZibProductPackage.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class ZibProductPackage(
    val content: List<Content>? = null
) {

    @Serializable
    data class Content(
        val reference: MgoReference? = null,
        val item: MgoCodeableConcept? = null
    )

}
