@file:Suppress("ktlint")

/*
 * ZibProduct.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class ZibProduct(
    val code: Code,
    val ingredient: List<Ingredient>? = null,
    val form: MgoCodeableConcept? = null,
    val profile: String = "http://nictiz.nl/fhir/StructureDefinition/zib-Product",
    val fhirVersion: String = "R3",
    val description: Description? = null,
    val id: String? = null,
    val referenceId: String,
    val resourceType: String
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str1) { "fhirVersion not constant value $cg_str1 - $fhirVersion" }
    }

    @Serializable
    data class Code(
        val coding: List<MgoCoding>? = null,
        val text: MgoString? = null
    )

    @Serializable
    data class Ingredient(
        val amount: MgoRatio? = null,
        val item_codeable_concept: MgoCodeableConcept? = null
    )

    @Serializable
    data class Description(
        val _type: String,
        val value: String,
        val _ext: Boolean
    ) {

        init {
            require(_type == cg_str2) { "_type not constant value $cg_str2 - $_type" }
        }

    }

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/zib-Product"
        private const val cg_str1 = "R3"
        private const val cg_str2 = "string"
    }

}
