@file:Suppress("ktlint")

/*
 * ZibProcedure.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class ZibProcedure(
    val identifier: List<MgoIdentifier>? = null,
    val code: MgoCodeableConcept? = null,
    val performer: List<Performer>? = null,
    val subject: MgoReference? = null,
    val profile: String = "http://nictiz.nl/fhir/StructureDefinition/zib-Procedure",
    val procedureMethod: ProcedureMethod? = null,
    val reasonReference: List<MgoReference>? = null,
    val focalDevice: List<FocalDevice>? = null,
    val performedPeriod: MgoPeriod? = null,
    val referenceId: String,
    val bodySite: List<BodySite>? = null,
    val fhirVersion: String = "R3",
    val report: List<MgoReference>? = null,
    val location: MgoReference? = null,
    val id: String? = null,
    val basedOn: List<MgoReference>? = null,
    val resourceType: String
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str2) { "fhirVersion not constant value $cg_str2 - $fhirVersion" }
    }

    @Serializable
    data class Performer(
        val actor: MgoReference? = null,
        val healthProfessionalRole: MgoCodeableConcept? = null
    )

    @Serializable
    data class ProcedureMethod(
        val coding: List<MgoCodingProps>,
        val _type: String,
        val text: String? = null,
        val _ext: Boolean
    ) {

        init {
            require(_type == cg_str1) { "_type not constant value $cg_str1 - $_type" }
        }

    }

    @Serializable
    data class FocalDevice(
        val manipulated: MgoReference? = null
    )

    @Serializable
    data class BodySite(
        val procedureLaterality: ProcedureLaterality? = null
    )

    @Serializable
    data class ProcedureLaterality(
        val coding: List<MgoCodingProps>,
        val _type: String,
        val text: String? = null,
        val _ext: Boolean
    ) {

        init {
            require(_type == cg_str1) { "_type not constant value $cg_str1 - $_type" }
        }

    }

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/zib-Procedure"
        private const val cg_str1 = "codeableConcept"
        private const val cg_str2 = "R3"
    }

}
