@file:Suppress("ktlint")

/*
 * ZibPayer.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class ZibPayer(
    val identifier: List<MgoIdentifier>? = null,
    val period: MgoPeriod? = null,
    val payor: List<Payor>? = null,
    val beneficiary: MgoReference? = null,
    val profile: String = "http://nictiz.nl/fhir/StructureDefinition/zib-Payer",
    val fhirVersion: String = "R3",
    val subscriberId: MgoString? = null,
    val id: String? = null,
    val type: MgoCodeableConcept? = null,
    val referenceId: String,
    val resourceType: String
) {

    init {
        require(profile == cg_str2) { "profile not constant value $cg_str2 - $profile" }
        require(fhirVersion == cg_str3) { "fhirVersion not constant value $cg_str3 - $fhirVersion" }
    }

    @Serializable
    data class Payor(
        val reference: String? = null,
        val bankInformation: List<BankInformation>,
        val display: String? = null,
        val _type: String? = null
    ) {

        init {
            if (_type != null)
                require(_type == cg_str1) { "_type not constant value $cg_str1 - $_type" }
        }

    }

    @Serializable
    data class BankInformation(
        val bankName: BankName? = null,
        val accountNumber: AccountNumber? = null,
        val _ext: Boolean,
        val bankcode: Bankcode? = null
    )

    @Serializable
    data class BankName(
        val _type: String,
        val value: String,
        val _ext: Boolean
    ) {

        init {
            require(_type == cg_str0) { "_type not constant value $cg_str0 - $_type" }
        }

    }

    @Serializable
    data class AccountNumber(
        val _type: String,
        val value: String,
        val _ext: Boolean
    ) {

        init {
            require(_type == cg_str0) { "_type not constant value $cg_str0 - $_type" }
        }

    }

    @Serializable
    data class Bankcode(
        val _type: String,
        val value: String,
        val _ext: Boolean
    ) {

        init {
            require(_type == cg_str0) { "_type not constant value $cg_str0 - $_type" }
        }

    }

    companion object {
        private const val cg_str0 = "string"
        private const val cg_str1 = "reference"
        private const val cg_str2 = "http://nictiz.nl/fhir/StructureDefinition/zib-Payer"
        private const val cg_str3 = "R3"
    }

}
