@file:Suppress("ktlint")

/*
 * ZibProblem.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class ZibProblem(
    val severity: MgoCodeableConcept? = null,
    val identifier: List<MgoIdentifier>? = null,
    val note: List<MgoAnnotation>? = null,
    val code: MgoCodeableConcept? = null,
    val evidence: List<Evidence>? = null,
    val verificationStatus: ZibProblemVerificationstatus? = null,
    val subject: MgoReference? = null,
    val abatementDateTime: MgoDateTime? = null,
    val profile: String = "http://nictiz.nl/fhir/StructureDefinition/zib-Problem",
    val clinicalStatus: ZibProblemClinicalstatus? = null,
    val onsetDateTime: MgoDateTime? = null,
    val assertedDate: MgoDateTime? = null,
    val referenceId: String,
    val bodySite: List<MgoCodeableConcept>? = null,
    val asserter: MgoReference? = null,
    val stage: Stage,
    val fhirVersion: String = "R3",
    val context: MgoReference? = null,
    val id: String? = null,
    val category: List<MgoCodeableConcept>? = null,
    val resourceType: String
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str1) { "fhirVersion not constant value $cg_str1 - $fhirVersion" }
    }

    @Serializable
    data class Evidence(
        val code: List<MgoCodeableConcept>? = null,
        val detail: List<MgoReference>? = null
    )

    @Serializable
    data class Stage(
        val summary: MgoCodeableConcept? = null,
        val assessment: List<MgoReference>? = null
    )

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/zib-Problem"
        private const val cg_str1 = "R3"
    }

}
