@file:Suppress("ktlint")

/*
 * ZibProblem.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class ZibProblem(
    val severity: MgoCodeableConcept? = null,
    val identifier: List<MgoIdentifier>? = null,
    val note: List<MgoAnnotation>? = null,
    val code: MgoCodeableConcept? = null,
    val evidence: List<Evidence>? = null,
    val verificationStatus: String? = null,
    val subject: MgoReference? = null,
    val abatementDateTime: String? = null,
    val profile: String,
    val clinicalStatus: ClinicalStatus? = null,
    val onsetDateTime: String? = null,
    val assertedDate: String? = null,
    val referenceId: String,
    val bodySite: List<MgoCodeableConcept>? = null,
    val asserter: MgoReference? = null,
    val stage: Stage,
    val fhirVersion: String,
    val context: MgoReference? = null,
    val id: String? = null,
    val category: List<MgoCodeableConcept>? = null,
    val resourceType: String? = null
) {

    init {
        if (verificationStatus != null)
            require(verificationStatus in cg_array0) { "verificationStatus not in enumerated values - $verificationStatus" }
        require(profile == cg_str1) { "profile not constant value $cg_str1 - $profile" }
        require(fhirVersion == cg_str2) { "fhirVersion not constant value $cg_str2 - $fhirVersion" }
    }

    @Serializable
    data class Evidence(
        val code: List<MgoCodeableConcept>? = null,
        val detail: List<MgoReference>? = null
    )

    @Serializable
    enum class ClinicalStatus {
        active,
        inactive,
        resolved,
        recurrence,
        remission
    }

    @Serializable
    data class Stage(
        val summary: MgoCodeableConcept? = null,
        val assessment: List<MgoReference>? = null
    )

    companion object {
        private val cg_array0 = setOf(
            "differential",
            "entered-in-error",
            "unknown",
            "confirmed",
            "refuted",
            "provisional"
        )
        private const val cg_str1 = "http://nictiz.nl/fhir/StructureDefinition/zib-Problem"
        private const val cg_str2 = "R3"
    }

}
