@file:Suppress("ktlint")

/*
 * ZibVaccination.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class ZibVaccination(
    val identifier: List<MgoIdentifier>? = null,
    val patient: MgoReference? = null,
    val vaccineCode: MgoCodeableConcept? = null,
    val dose: MgoQuantity? = null,
    val vaccinationDate: String? = null,
    val practitioner: List<Practitioner>? = null,
    val note: List<MgoAnnotation>? = null,
    val id: String? = null,
    val referenceId: String,
    val resourceType: String? = null,
    val profile: String,
    val fhirVersion: String
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str1) { "fhirVersion not constant value $cg_str1 - $fhirVersion" }
    }

    @Serializable
    data class Practitioner(
        val actor: MgoReference? = null
    )

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/zib-Vaccination"
        private const val cg_str1 = "R3"
    }

}
