@file:Suppress("ktlint")

/*
 * ZibVaccinationRecommendation.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package nl.rijksoverheid.mgo.data.fhirParser.models

import kotlinx.serialization.Serializable

@Serializable
data class ZibVaccinationRecommendation(
    val identifier: List<MgoIdentifier>? = null,
    val subject: MgoReference? = null,
    val profile: String = "http://nictiz.nl/fhir/StructureDefinition/zib-VaccinationRecommendation",
    val fhirVersion: String = "R3",
    val orderStatus: OrderStatus? = null,
    val recommendation: List<Recommendation>? = null,
    val id: String? = null,
    val referenceId: String,
    val resourceType: String
) {

    init {
        require(profile == cg_str0) { "profile not constant value $cg_str0 - $profile" }
        require(fhirVersion == cg_str1) { "fhirVersion not constant value $cg_str1 - $fhirVersion" }
    }

    @Serializable
    data class OrderStatus(
        val coding: List<MgoCodingProps>,
        val _type: String,
        val text: String? = null,
        val _ext: Boolean
    ) {

        init {
            require(_type == cg_str2) { "_type not constant value $cg_str2 - $_type" }
        }

    }

    @Serializable
    data class Recommendation(
        val date: MgoDateTime? = null,
        val supportingImmunization: List<MgoReference>? = null,
        val vaccineCode: MgoCodeableConcept? = null,
        val dateCriterion: List<MgoDateTime>? = null
    )

    companion object {
        private const val cg_str0 = "http://nictiz.nl/fhir/StructureDefinition/zib-VaccinationRecommendation"
        private const val cg_str1 = "R3"
        private const val cg_str2 = "codeableConcept"
    }

}
