name: 'CI/CD'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    name: Run E2E Tests
    runs-on: macos-13

    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
      KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
      BASIC_AUTH_USER: ${{ secrets.BASIC_AUTH_USER }}
      BASIC_AUTH_PASSWORD: ${{ secrets.BASIC_AUTH_PASSWORD }}

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Run instrumented tests in app module
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: |
            ./gradlew connectedTstDebugAndroidTest
            echo "Waiting for emulator..."
            adb wait-for-device
            adb shell ls /data/data/nl.rijksoverheid.mgo.tst/cache/screenshots || echo "No screenshots"
            adb pull /data/data/nl.rijksoverheid.mgo.tst/cache/screenshots ./screenshots
          heap-size: 1024M
          memory: 2G
          cores: 2
          disable-animations: true

      - name: Upload screenshots artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: android-screenshots
          path: ./screenshots
