name: 'Run CI/CD'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3  
      - name: Lint
        run: ./gradlew lintTstDebug
      - name: Unit Tests
        run: ./gradlew testTstDebug
      - name: Android Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedTstDebugAndroidTest
          profile: pixel
      - name: Archive Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            app/build/reports
          retention-days: 5
      - name: Download Keystore
        run: echo $KEYSTORE_FILE | base64 --decode > mgo.keystore
      - name: Build Apps
        run: ./gradlew assembleTstRelease assembleAccRelease assembleProdRelease
      - name: Archive Apps
        uses: actions/upload-artifact@v4
        with:
          name: apks
          path: |
            app/build/outputs/apk
          retention-days: 5
      - name: Distribute Apps
        uses: ./gradlew appDistributionUploadTstRelease appDistributionUploadAccRelease appDistributionUploadProdRelease